#include "esphome_api.h"
#include "private/esphome_api_codec.h"
#include "esphome_noise.h"
#include "esp_random.h"
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <sys/time.h>
#include "lwip/netdb.h"
#include "lwip/sockets.h"
#define MAGIC 0x45415049u
#define DEF_TO 5000u
#define BADFD (-1)
typedef struct { uint32_t magic; int sock; uint32_t timeout_ms; uint16_t port,max_frame; char host[ESPHOME_API_MAX_HOST_LEN+1]; esphome_api_state_fn state_cb; void *state_user; esphome_api_protocol_error_t protocol_error; bool initialized,connected,hello_done,probed,subscribed,noise_requested,noise_ready; uint32_t drop_streak,entropy_calls; uint8_t noise_psk[ESPHOME_NOISE_PSK_BYTES]; union { esphome_noise_handshake_t hs; uint8_t frame[ESPHOME_API_MAX_FRAME_BYTES]; } u; esphome_noise_cipherstate_t tx,rx; } impl_t;
_Static_assert(sizeof(impl_t)<=ESPHOME_API_SESSION_BYTES,"increase ESPHOME_API_SESSION_BYTES");
static impl_t*I(esphome_api_session_t*s){return (void*)s;} static const impl_t*CI(const esphome_api_session_t*s){return (const void*)s;} static bool valid(const impl_t*i){return i&&i->magic==MAGIC&&i->initialized;}
static void sto(int fd,uint32_t ms){struct timeval tv={.tv_sec=(time_t)(ms/1000u),.tv_usec=(suseconds_t)((ms%1000u)*1000u)};(void)setsockopt(fd,SOL_SOCKET,SO_RCVTIMEO,&tv,sizeof(tv));(void)setsockopt(fd,SOL_SOCKET,SO_SNDTIMEO,&tv,sizeof(tv));}
static void nwipe(impl_t*i);
static void hardclose(impl_t*i){if(i->sock!=BADFD){shutdown(i->sock,SHUT_RDWR);close(i->sock);}i->sock=BADFD;i->connected=i->hello_done=i->probed=i->subscribed=false;i->state_cb=NULL;i->state_user=NULL;i->drop_streak=0;if(i->noise_requested)nwipe(i);}
static esp_err_t ioerr(impl_t*i){int e=errno;i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_IO;hardclose(i);return (e==EAGAIN||e==EWOULDBLOCK||e==ETIMEDOUT)?ESP_ERR_TIMEOUT:ESP_FAIL;}
static esp_err_t connect_one(int fd,const struct sockaddr*addr,socklen_t addrlen,uint32_t timeout_ms){
    int flags=fcntl(fd,F_GETFL,0);
    if(flags<0||fcntl(fd,F_SETFL,flags|O_NONBLOCK)<0)return ESP_FAIL;
    if(connect(fd,addr,addrlen)==0){(void)fcntl(fd,F_SETFL,flags);return ESP_OK;}
    if(errno!=EINPROGRESS&&errno!=EWOULDBLOCK){(void)fcntl(fd,F_SETFL,flags);return ESP_FAIL;}
    fd_set wf;FD_ZERO(&wf);FD_SET(fd,&wf);
    struct timeval tv={.tv_sec=(time_t)(timeout_ms/1000u),.tv_usec=(suseconds_t)((timeout_ms%1000u)*1000u)};
    int sr=select(fd+1,NULL,&wf,NULL,&tv);
    if(sr==0){errno=ETIMEDOUT;(void)fcntl(fd,F_SETFL,flags);return ESP_ERR_TIMEOUT;}
    if(sr<0){(void)fcntl(fd,F_SETFL,flags);return ESP_FAIL;}
    int soerr=0;socklen_t sl=(socklen_t)sizeof(soerr);
    if(getsockopt(fd,SOL_SOCKET,SO_ERROR,&soerr,&sl)<0){(void)fcntl(fd,F_SETFL,flags);return ESP_FAIL;}
    (void)fcntl(fd,F_SETFL,flags);
    if(soerr){errno=soerr;return soerr==ETIMEDOUT?ESP_ERR_TIMEOUT:ESP_FAIL;}
    return ESP_OK;
}
static esp_err_t csock(impl_t*i){if(i->connected)return ESP_OK;char ps[6];(void)snprintf(ps,sizeof(ps),"%u",(unsigned)i->port);struct addrinfo h={0},*res=NULL;h.ai_family=AF_UNSPEC;h.ai_socktype=SOCK_STREAM;if(getaddrinfo(i->host,ps,&h,&res)!=0||!res){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_IO;return ESP_FAIL;}esp_err_t e=ESP_FAIL;for(struct addrinfo*p=res;p;p=p->ai_next){int fd=socket(p->ai_family,p->ai_socktype,p->ai_protocol);if(fd<0)continue;esp_err_t ce=connect_one(fd,p->ai_addr,(socklen_t)p->ai_addrlen,i->timeout_ms);if(ce==ESP_OK){sto(fd,i->timeout_ms);i->sock=fd;i->connected=true;i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_NONE;e=ESP_OK;break;}if(ce==ESP_ERR_TIMEOUT)e=ESP_ERR_TIMEOUT;close(fd);}freeaddrinfo(res);if(e!=ESP_OK)i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_IO;return e;}
static bool sall(int fd,const uint8_t*p,size_t n){while(n){ssize_t w=send(fd,p,n,0);if(w<=0)return false;p+=(size_t)w;n-=(size_t)w;}return true;} static bool rall(int fd,uint8_t*p,size_t n){while(n){ssize_t r=recv(fd,p,n,0);if(r<=0)return false;p+=(size_t)r;n-=(size_t)r;}return true;}
/* Noise transport. The handshake material lives in *u.hs and is wiped at split;
 * the transport ciphers live in tx/rx and are wiped on every close. */
static void nentropy(void*u,uint8_t*out,size_t len){impl_t*i=u;i->entropy_calls++;esp_fill_random(out,len);} static void nwipe(impl_t*i){esphome_noise_handshake_wipe(&i->u.hs);esphome_noise_cipherstate_wipe(&i->tx);esphome_noise_cipherstate_wipe(&i->rx);i->noise_ready=false;}
static bool noise_build(impl_t*i,uint16_t type,const uint8_t*payload,size_t n,uint8_t*out,size_t cap,size_t*out_len){uint8_t pt[4+ESPHOME_API_MAX_FRAME_BYTES];size_t enc=0;if(n>sizeof(pt)-4u||cap<3u)return false;pt[0]=(uint8_t)(type>>8);pt[1]=(uint8_t)(type&0xffu);pt[2]=(uint8_t)(n>>8);pt[3]=(uint8_t)(n&0xffu);if(n)memcpy(pt+4,payload,n);if(esphome_noise_encrypt(&i->tx,NULL,0,pt,4+n,out+3,cap-3,&enc)!=ESPHOME_NOISE_OK)return false;out[0]=ESPHOME_NOISE_PREAMBLE;out[1]=(uint8_t)(enc>>8);out[2]=(uint8_t)(enc&0xffu);*out_len=3+enc;return true;}
static bool noise_unwrap(impl_t*i,const uint8_t*frame,size_t flen,uint16_t*type,size_t*n){uint8_t pt[ESPHOME_API_MAX_FRAME_BYTES];size_t plen=0;if(flen<ESPHOME_NOISE_TAG_BYTES)return false;if(esphome_noise_decrypt(&i->rx,NULL,0,frame,flen,pt,sizeof(pt),&plen)!=ESPHOME_NOISE_OK)return false;if(plen<4u)return false;*type=(uint16_t)(((uint16_t)pt[0]<<8)|pt[1]);*n=plen-4u;memmove(i->u.frame,pt+4,*n);return true;}
static esp_err_t noise_client_hello(impl_t*i){/* The last reported cause must not carry a value from an earlier connection
 * into this handshake's failure: a stale OVERSIZED once sent a whole round of
 * investigation after the wrong bug. */i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_NONE;uint8_t msg[ESPHOME_NOISE_HANDSHAKE_MSG_BYTES],hs[ESPHOME_NOISE_HANDSHAKE_MSG_BYTES],wr[3+ESPHOME_NOISE_HANDSHAKE_MSG_BYTES];size_t hl=0,wl=0;if(sizeof(hs)>i->max_frame){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_OVERSIZED;hardclose(i);return ESP_ERR_INVALID_SIZE;}if(esphome_noise_initiator_init(&i->u.hs,i->noise_psk,ESPHOME_NOISE_PSK_BYTES,(const uint8_t*)ESPHOME_NOISE_PROLOGUE,ESPHOME_NOISE_PROLOGUE_LEN,nentropy,i)!=ESPHOME_NOISE_OK){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_NOISE_NOT_SUPPORTED;hardclose(i);return ESP_FAIL;}if(esphome_noise_write_message(&i->u.hs,msg,sizeof(msg),&hl)!=ESPHOME_NOISE_OK||hl!=sizeof(msg)){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_NOISE_NOT_SUPPORTED;hardclose(i);return ESP_FAIL;}wr[0]=ESPHOME_NOISE_PREAMBLE;wr[1]=(uint8_t)(hl>>8);wr[2]=(uint8_t)(hl&0xffu);memcpy(wr+3,msg,hl);/* aioesphomeapi sends NOISE_HELLO = 00 01 00 00 before the handshake, and the peer reads it before anything else: it is how a peer that still accepts plaintext learns this connection is encrypted. */if(!sall(i->sock,esphome_noise_client_hello_marker(),4))return ioerr(i);if(!sall(i->sock,wr,3+hl)){return ioerr(i);}if(!rall(i->sock,hs,sizeof(hs))){return ioerr(i);}if(hs[0]!=ESPHOME_NOISE_PREAMBLE){i->protocol_error=hs[0]==0?ESPHOME_API_PROTOCOL_ERROR_ENCRYPTION_REQUIRED:ESPHOME_API_PROTOCOL_ERROR_MALFORMED;hardclose(i);return ESP_ERR_INVALID_RESPONSE;}if(hs[1]!=0){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_AUTH_REQUIRED;hardclose(i);return ESP_ERR_INVALID_RESPONSE;}/* hs[2] is the length of the handshake message that follows. The reply is
 * read in full before the length is checked, so the read and the check agree:
 * the handshake message is always ESPHOME_NOISE_HANDSHAKE_MSG_BYTES. */if(hs[2]!=ESPHOME_NOISE_HANDSHAKE_MSG_BYTES){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_MALFORMED;hardclose(i);return ESP_ERR_INVALID_RESPONSE;}{esphome_noise_err_t rm=esphome_noise_read_message(&i->u.hs,hs+3,hs[2]);if(rm!=ESPHOME_NOISE_OK){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_AUTH_REQUIRED;hardclose(i);return ESP_ERR_INVALID_RESPONSE;}}if(esphome_noise_split(&i->u.hs,&i->tx,&i->rx)!=ESPHOME_NOISE_OK){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_NOISE_NOT_SUPPORTED;hardclose(i);return ESP_FAIL;}esphome_noise_handshake_wipe(&i->u.hs);i->noise_ready=true;wl=0;if(!noise_build(i,0,NULL,0,i->u.frame,sizeof(i->u.frame),&wl)||!sall(i->sock,i->u.frame,wl))return ioerr(i);return ESP_OK;}
static size_t rv(uint64_t v,uint8_t*out){size_t n=0;do{uint8_t b=(uint8_t)(v&0x7f);v>>=7;if(v)b|=0x80;out[n++]=b;}while(v);return n;}
static esp_err_t sendp(impl_t*i,uint16_t t,const uint8_t*p,size_t n){if(!i->connected)return ESP_ERR_INVALID_STATE;if(n>i->max_frame)return ESP_ERR_INVALID_SIZE;uint8_t h[12];size_t k=0;h[k++]=0;k+=rv(n,h+k);k+=rv(t,h+k);if(!sall(i->sock,h,k)||(n&&!sall(i->sock,p,n)))return ioerr(i);return ESP_OK;}
static esp_err_t recvv(impl_t*i,uint32_t*out){uint32_t v=0;unsigned sh=0;for(unsigned n=0;n<4;n++){uint8_t b;if(!rall(i->sock,&b,1))return ioerr(i);v|=(uint32_t)(b&0x7f)<<sh;if(!(b&0x80)){*out=v;return ESP_OK;}sh+=7;}i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_MALFORMED;hardclose(i);return ESP_ERR_INVALID_RESPONSE;}
static esp_err_t recvp(impl_t*i,uint16_t*t,size_t*n,uint32_t timeout){if(!i->connected)return ESP_ERR_INVALID_STATE;sto(i->sock,timeout?timeout:i->timeout_ms);uint8_t pre;if(!rall(i->sock,&pre,1))return ioerr(i);if(pre!=0){i->protocol_error=pre==1?ESPHOME_API_PROTOCOL_ERROR_ENCRYPTION_REQUIRED:ESPHOME_API_PROTOCOL_ERROR_MALFORMED;hardclose(i);return pre==1?ESP_ERR_NOT_SUPPORTED:ESP_ERR_INVALID_RESPONSE;}uint32_t len=0,type=0;esp_err_t e=recvv(i,&len);if(e!=ESP_OK)return e;e=recvv(i,&type);if(e!=ESP_OK)return e;if(type>UINT16_MAX){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_MALFORMED;hardclose(i);return ESP_ERR_INVALID_RESPONSE;}if(len>i->max_frame||len>sizeof(i->u.frame)){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_OVERSIZED;hardclose(i);return ESP_ERR_INVALID_SIZE;}if(len&&!rall(i->sock,i->u.frame,len))return ioerr(i);*t=(uint16_t)type;*n=len;return ESP_OK;}
/* Reads one encrypted frame. A frame that fails authentication is dropped, never
 * dispatched; a peer that keeps sending unauthenticated bytes is disconnected so a
 * hostile or corrupt link cannot keep the client spinning. */
static esp_err_t recvn(impl_t*i,uint16_t*t,size_t*n,uint32_t timeout){if(!i->connected)return ESP_ERR_INVALID_STATE;if(!i->noise_ready){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_NOISE_NOT_SUPPORTED;return ESP_ERR_INVALID_STATE;}for(;;){sto(i->sock,timeout?timeout:i->timeout_ms);uint8_t h[3];if(!rall(i->sock,h,sizeof(h))){return ioerr(i);}if(h[0]!=ESPHOME_NOISE_PREAMBLE){i->protocol_error=h[0]==0?ESPHOME_API_PROTOCOL_ERROR_ENCRYPTION_REQUIRED:ESPHOME_API_PROTOCOL_ERROR_MALFORMED;hardclose(i);return ESP_ERR_INVALID_RESPONSE;}size_t flen=((size_t)h[1]<<8)|(size_t)h[2];if(flen<ESPHOME_NOISE_TAG_BYTES||flen>i->max_frame){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_OVERSIZED;hardclose(i);return ESP_ERR_INVALID_SIZE;}if(!rall(i->sock,i->u.frame,flen))return ioerr(i);if(noise_unwrap(i,i->u.frame,flen,t,n))return ESP_OK;if(++i->drop_streak>=ESPHOME_API_MAX_DROP_FRAMES){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_MALFORMED;hardclose(i);return ESP_ERR_INVALID_RESPONSE;}}}
static esp_err_t sendn(impl_t*i,uint16_t t,const uint8_t*p,size_t n){uint8_t out[3+4+ESPHOME_API_MAX_FRAME_BYTES];size_t len=0;if(n>i->max_frame)return ESP_ERR_INVALID_SIZE;if(!noise_build(i,t,p,n,out,sizeof(out),&len))return ioerr(i);if(!sall(i->sock,out,len))return ioerr(i);return ESP_OK;}
static esp_err_t sendf(impl_t*i,uint16_t t,const uint8_t*p,size_t n){if(!i->noise_requested)return sendp(i,t,p,n);if(!i->noise_ready)return ESP_ERR_INVALID_STATE;return sendn(i,t,p,n);}
static esp_err_t recvf(impl_t*i,uint16_t*t,size_t*n,uint32_t timeout){return i->noise_requested?recvn(i,t,n,timeout):recvp(i,t,n,timeout);}
static esp_err_t control(impl_t*i,uint16_t t,bool*handled){*handled=false;if(t==7){*handled=true;return sendf(i,8,NULL,0);}if(t==36){/* Read-only interrogation must not mutate peer time. */*handled=true;return ESP_OK;}if(t==5){*handled=true;(void)sendf(i,6,NULL,0);i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_PEER_DISCONNECTED;hardclose(i);return ESP_ERR_INVALID_STATE;}return ESP_OK;}
static esp_err_t waittype(impl_t*i,uint16_t want,size_t*n){for(unsigned g=0;g<16;g++){uint16_t t;size_t l;esp_err_t e=recvf(i,&t,&l,i->timeout_ms);if(e!=ESP_OK)return e;bool h;e=control(i,t,&h);if(e!=ESP_OK)return e;if(h)continue;if(t!=want){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_UNEXPECTED_MESSAGE;return ESP_ERR_INVALID_RESPONSE;}*n=l;return ESP_OK;}return ESP_ERR_TIMEOUT;}
static esp_err_t hello(impl_t*i,esphome_api_probe_result_t*out){esp_err_t e=csock(i);if(e!=ESP_OK)return e;if(i->hello_done)return ESP_OK;if(i->noise_requested&&!i->noise_ready){e=noise_client_hello(i);if(e!=ESP_OK)return e;}uint8_t p[64];size_t n;if(!esphome_api_codec_hello_request(p,sizeof(p),&n))return ESP_FAIL;e=sendf(i,1,p,n);if(e!=ESP_OK)return e;size_t l;e=waittype(i,2,&l);if(e!=ESP_OK)return e;esphome_api_probe_result_t tmp={0};if(!esphome_api_codec_parse_hello(i->u.frame,l,out?out:&tmp)){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_MALFORMED;hardclose(i);return ESP_ERR_INVALID_RESPONSE;}i->hello_done=true;return ESP_OK;}
esp_err_t esphome_api_init(esphome_api_session_t*s,const esphome_api_config_t*c){if(!s||!c||!c->host)return ESP_ERR_INVALID_ARG;size_t h=strnlen(c->host,ESPHOME_API_MAX_HOST_LEN+1);if(!h||h>ESPHOME_API_MAX_HOST_LEN)return ESP_ERR_INVALID_ARG;if((c->noise_psk==NULL)!=(c->noise_psk_len==0))return ESP_ERR_INVALID_ARG;if(c->noise_psk&&c->noise_psk_len!=32)return ESP_ERR_INVALID_ARG;if(c->max_frame_bytes>ESPHOME_API_MAX_FRAME_BYTES)return ESP_ERR_INVALID_ARG;memset(s,0,sizeof(*s));impl_t*i=I(s);i->magic=MAGIC;i->sock=BADFD;i->timeout_ms=c->timeout_ms?c->timeout_ms:DEF_TO;i->port=c->port?c->port:ESPHOME_API_DEFAULT_PORT;i->max_frame=c->max_frame_bytes?c->max_frame_bytes:ESPHOME_API_MAX_FRAME_BYTES;memcpy(i->host,c->host,h);i->host[h]=0;i->noise_requested=c->noise_psk!=NULL;/* The key is copied, not borrowed: the caller's buffer need not outlive this call, and the handshake reads it later. */if(c->noise_psk)memcpy(i->noise_psk,c->noise_psk,ESPHOME_NOISE_PSK_BYTES);i->initialized=true;return ESP_OK;}
void esphome_api_deinit(esphome_api_session_t*s){if(!s)return;impl_t*i=I(s);if(valid(i))hardclose(i);if(i->magic==MAGIC)noise_crypto_wipe(i->noise_psk,sizeof(i->noise_psk));memset(s,0,sizeof(*s));}
esp_err_t esphome_api_probe(esphome_api_session_t*s,esphome_api_probe_result_t*out){if(!s||!out)return ESP_ERR_INVALID_ARG;impl_t*i=I(s);if(!valid(i))return ESP_ERR_INVALID_STATE;memset(out,0,sizeof(*out));esp_err_t e=hello(i,out);if(e!=ESP_OK){return e;}e=sendf(i,9,NULL,0);if(e!=ESP_OK){return e;}if(e!=ESP_OK)return e;size_t l;e=waittype(i,10,&l);if(e!=ESP_OK)return e;if(!esphome_api_codec_parse_device_info(i->u.frame,l,out)){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_MALFORMED;hardclose(i);return ESP_ERR_INVALID_RESPONSE;}i->probed=true;return ESP_OK;}
esp_err_t esphome_api_entities(esphome_api_session_t*s,esphome_api_entity_list_t*out){if(!s||!out||(out->capacity&&!out->items))return ESP_ERR_INVALID_ARG;impl_t*i=I(s);if(!valid(i))return ESP_ERR_INVALID_STATE;esp_err_t e=hello(i,NULL);if(e!=ESP_OK)return e;out->count=out->total_seen=out->unsupported_seen=0;out->truncated=false;e=sendf(i,11,NULL,0);if(e!=ESP_OK)return e;for(size_t g=0;g<1024;g++){uint16_t t;size_t l;e=recvf(i,&t,&l,i->timeout_ms);if(e!=ESP_OK)return e;bool h;e=control(i,t,&h);if(e!=ESP_OK)return e;if(h)continue;if(t==19)return ESP_OK;esphome_api_entity_t ent;if(esphome_api_codec_parse_entity(t,i->u.frame,l,&ent)){out->total_seen++;if(out->count<out->capacity)out->items[out->count++]=ent;else out->truncated=true;}else out->unsupported_seen++;}i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_MALFORMED;hardclose(i);return ESP_ERR_INVALID_RESPONSE;}
esp_err_t esphome_api_subscribe(esphome_api_session_t*s,esphome_api_state_fn cb,void*u){if(!s||!cb)return ESP_ERR_INVALID_ARG;impl_t*i=I(s);if(!valid(i))return ESP_ERR_INVALID_STATE;esp_err_t e=hello(i,NULL);if(e!=ESP_OK)return e;e=sendf(i,20,NULL,0);if(e==ESP_OK){i->state_cb=cb;i->state_user=u;i->subscribed=true;}return e;}
esp_err_t esphome_api_poll(esphome_api_session_t*s,uint32_t timeout){if(!s)return ESP_ERR_INVALID_ARG;impl_t*i=I(s);if(!valid(i)||!i->connected||!i->subscribed)return ESP_ERR_INVALID_STATE;uint16_t t;size_t l;esp_err_t e=recvf(i,&t,&l,timeout);if(e!=ESP_OK)return e;bool h;e=control(i,t,&h);if(e!=ESP_OK||h)return e;esphome_api_state_t st;if(esphome_api_codec_parse_state(t,i->u.frame,l,&st)){i->state_cb(&st,i->state_user);return ESP_OK;}return ESP_OK;}
/* Command transport requires the authenticated channel. Without a PSK there is no
 * authentication, so a command is refused instead of sent in the clear. A
 * successful send is not a state change: the observed state moves only when the
 * peer reports it through the subscription callback. */
esp_err_t esphome_api_command(esphome_api_session_t*s,const esphome_api_command_t*c){if(!s||!c)return ESP_ERR_INVALID_ARG;impl_t*i=I(s);if(!valid(i))return ESP_ERR_INVALID_STATE;if(!i->connected)return ESP_ERR_INVALID_STATE;if(!i->noise_requested){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_AUTH_REQUIRED;return ESP_ERR_NOT_SUPPORTED;}if(!i->noise_ready)return ESP_ERR_INVALID_STATE;uint16_t t;size_t n;uint8_t p[256];if(!esphome_api_codec_command(c,&t,p,sizeof(p),&n))return ESP_ERR_INVALID_ARG;return sendf(i,t,p,n);}
esp_err_t esphome_api_close(esphome_api_session_t*s){if(!s)return ESP_ERR_INVALID_ARG;impl_t*i=I(s);if(!valid(i))return ESP_ERR_INVALID_STATE;if(!i->connected)return ESP_OK;esp_err_t e=sendf(i,5,NULL,0);if(e==ESP_OK){uint16_t t;size_t l;esp_err_t r=recvf(i,&t,&l,i->timeout_ms);if(r==ESP_OK&&t!=6)r=ESP_ERR_INVALID_RESPONSE;if(r!=ESP_OK)e=r;}hardclose(i);return e;}
void esphome_api_cancel(esphome_api_session_t*s){if(!s)return;impl_t*i=I(s);if(valid(i))hardclose(i);} bool esphome_api_is_connected(const esphome_api_session_t*s){if(!s)return false;const impl_t*i=CI(s);return valid(i)&&i->connected;} esphome_api_protocol_error_t esphome_api_last_protocol_error(const esphome_api_session_t*s){if(!s)return ESPHOME_API_PROTOCOL_ERROR_NONE;const impl_t*i=CI(s);return i->magic==MAGIC?i->protocol_error:ESPHOME_API_PROTOCOL_ERROR_NONE;}
