#include "esphome_api.h"
#include "private/esphome_api_codec.h"
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <sys/time.h>
#include "lwip/netdb.h"
#include "lwip/sockets.h"
#define MAGIC 0x45415049u
#define DEF_TO 5000u
#define BADFD (-1)
typedef struct { uint32_t magic; int sock; uint32_t timeout_ms; uint16_t port,max_frame; char host[ESPHOME_API_MAX_HOST_LEN+1]; esphome_api_state_fn state_cb; void *state_user; esphome_api_protocol_error_t protocol_error; bool initialized,connected,hello_done,probed,subscribed,noise_requested; uint8_t frame[ESPHOME_API_MAX_FRAME_BYTES]; } impl_t;
_Static_assert(sizeof(impl_t)<=ESPHOME_API_SESSION_BYTES,"increase ESPHOME_API_SESSION_BYTES");
static impl_t*I(esphome_api_session_t*s){return (void*)s;} static const impl_t*CI(const esphome_api_session_t*s){return (const void*)s;} static bool valid(const impl_t*i){return i&&i->magic==MAGIC&&i->initialized;}
static void sto(int fd,uint32_t ms){struct timeval tv={.tv_sec=(time_t)(ms/1000u),.tv_usec=(suseconds_t)((ms%1000u)*1000u)};(void)setsockopt(fd,SOL_SOCKET,SO_RCVTIMEO,&tv,sizeof(tv));(void)setsockopt(fd,SOL_SOCKET,SO_SNDTIMEO,&tv,sizeof(tv));}
static void hardclose(impl_t*i){if(i->sock!=BADFD){shutdown(i->sock,SHUT_RDWR);close(i->sock);}i->sock=BADFD;i->connected=i->hello_done=i->probed=i->subscribed=false;i->state_cb=NULL;i->state_user=NULL;}
static esp_err_t ioerr(impl_t*i){int e=errno;i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_IO;hardclose(i);return (e==EAGAIN||e==EWOULDBLOCK||e==ETIMEDOUT)?ESP_ERR_TIMEOUT:ESP_FAIL;}
static esp_err_t connect_one(int fd,const struct sockaddr*addr,socklen_t addrlen,uint32_t timeout_ms){
    int flags=fcntl(fd,F_GETFL,0);
    if(flags<0||fcntl(fd,F_SETFL,flags|O_NONBLOCK)<0)return ESP_FAIL;
    if(connect(fd,addr,addrlen)==0){(void)fcntl(fd,F_SETFL,flags);return ESP_OK;}
    if(errno!=EINPROGRESS&&errno!=EWOULDBLOCK){(void)fcntl(fd,F_SETFL,flags);return ESP_FAIL;}
    fd_set wf;FD_ZERO(&wf);FD_SET(fd,&wf);
    struct timeval tv={.tv_sec=(time_t)(timeout_ms/1000u),.tv_usec=(suseconds_t)((timeout_ms%1000u)*1000u)};
    int sr=select(fd+1,NULL,&wf,NULL,&tv);
    if(sr==0){errno=ETIMEDOUT;(void)fcntl(fd,F_SETFL,flags);return ESP_ERR_TIMEOUT;}
    if(sr<0){(void)fcntl(fd,F_SETFL,flags);return ESP_FAIL;}
    int soerr=0;socklen_t sl=(socklen_t)sizeof(soerr);
    if(getsockopt(fd,SOL_SOCKET,SO_ERROR,&soerr,&sl)<0){(void)fcntl(fd,F_SETFL,flags);return ESP_FAIL;}
    (void)fcntl(fd,F_SETFL,flags);
    if(soerr){errno=soerr;return soerr==ETIMEDOUT?ESP_ERR_TIMEOUT:ESP_FAIL;}
    return ESP_OK;
}
static esp_err_t csock(impl_t*i){if(i->connected)return ESP_OK;if(i->noise_requested){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_NOISE_NOT_SUPPORTED;return ESP_ERR_NOT_SUPPORTED;}char ps[6];(void)snprintf(ps,sizeof(ps),"%u",(unsigned)i->port);struct addrinfo h={0},*res=NULL;h.ai_family=AF_UNSPEC;h.ai_socktype=SOCK_STREAM;if(getaddrinfo(i->host,ps,&h,&res)!=0||!res){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_IO;return ESP_FAIL;}esp_err_t e=ESP_FAIL;for(struct addrinfo*p=res;p;p=p->ai_next){int fd=socket(p->ai_family,p->ai_socktype,p->ai_protocol);if(fd<0)continue;esp_err_t ce=connect_one(fd,p->ai_addr,(socklen_t)p->ai_addrlen,i->timeout_ms);if(ce==ESP_OK){sto(fd,i->timeout_ms);i->sock=fd;i->connected=true;i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_NONE;e=ESP_OK;break;}if(ce==ESP_ERR_TIMEOUT)e=ESP_ERR_TIMEOUT;close(fd);}freeaddrinfo(res);if(e!=ESP_OK)i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_IO;return e;}
static bool sall(int fd,const uint8_t*p,size_t n){while(n){ssize_t w=send(fd,p,n,0);if(w<=0)return false;p+=(size_t)w;n-=(size_t)w;}return true;} static bool rall(int fd,uint8_t*p,size_t n){while(n){ssize_t r=recv(fd,p,n,0);if(r<=0)return false;p+=(size_t)r;n-=(size_t)r;}return true;}
static size_t rv(uint64_t v,uint8_t*out){size_t n=0;do{uint8_t b=(uint8_t)(v&0x7f);v>>=7;if(v)b|=0x80;out[n++]=b;}while(v);return n;}
static esp_err_t sendf(impl_t*i,uint16_t t,const uint8_t*p,size_t n){if(!i->connected)return ESP_ERR_INVALID_STATE;if(n>i->max_frame)return ESP_ERR_INVALID_SIZE;uint8_t h[12];size_t k=0;h[k++]=0;k+=rv(n,h+k);k+=rv(t,h+k);if(!sall(i->sock,h,k)||(n&&!sall(i->sock,p,n)))return ioerr(i);return ESP_OK;}
static esp_err_t recvv(impl_t*i,uint32_t*out){uint32_t v=0;unsigned sh=0;for(unsigned n=0;n<4;n++){uint8_t b;if(!rall(i->sock,&b,1))return ioerr(i);v|=(uint32_t)(b&0x7f)<<sh;if(!(b&0x80)){*out=v;return ESP_OK;}sh+=7;}i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_MALFORMED;hardclose(i);return ESP_ERR_INVALID_RESPONSE;}
static esp_err_t recvf(impl_t*i,uint16_t*t,size_t*n,uint32_t timeout){if(!i->connected)return ESP_ERR_INVALID_STATE;sto(i->sock,timeout?timeout:i->timeout_ms);uint8_t pre;if(!rall(i->sock,&pre,1))return ioerr(i);if(pre!=0){i->protocol_error=pre==1?ESPHOME_API_PROTOCOL_ERROR_ENCRYPTION_REQUIRED:ESPHOME_API_PROTOCOL_ERROR_MALFORMED;hardclose(i);return pre==1?ESP_ERR_NOT_SUPPORTED:ESP_ERR_INVALID_RESPONSE;}uint32_t len=0,type=0;esp_err_t e=recvv(i,&len);if(e!=ESP_OK)return e;e=recvv(i,&type);if(e!=ESP_OK)return e;if(type>UINT16_MAX){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_MALFORMED;hardclose(i);return ESP_ERR_INVALID_RESPONSE;}if(len>i->max_frame||len>sizeof(i->frame)){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_OVERSIZED;hardclose(i);return ESP_ERR_INVALID_SIZE;}if(len&&!rall(i->sock,i->frame,len))return ioerr(i);*t=(uint16_t)type;*n=len;return ESP_OK;}
static esp_err_t control(impl_t*i,uint16_t t,bool*handled){*handled=false;if(t==7){*handled=true;return sendf(i,8,NULL,0);}if(t==36){/* Read-only interrogation must not mutate peer time. */*handled=true;return ESP_OK;}if(t==5){*handled=true;(void)sendf(i,6,NULL,0);i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_PEER_DISCONNECTED;hardclose(i);return ESP_ERR_INVALID_STATE;}return ESP_OK;}
static esp_err_t waittype(impl_t*i,uint16_t want,size_t*n){for(unsigned g=0;g<16;g++){uint16_t t;size_t l;esp_err_t e=recvf(i,&t,&l,i->timeout_ms);if(e!=ESP_OK)return e;bool h;e=control(i,t,&h);if(e!=ESP_OK)return e;if(h)continue;if(t!=want){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_UNEXPECTED_MESSAGE;return ESP_ERR_INVALID_RESPONSE;}*n=l;return ESP_OK;}return ESP_ERR_TIMEOUT;}
static esp_err_t hello(impl_t*i,esphome_api_probe_result_t*out){esp_err_t e=csock(i);if(e!=ESP_OK)return e;if(i->hello_done)return ESP_OK;uint8_t p[64];size_t n;if(!esphome_api_codec_hello_request(p,sizeof(p),&n))return ESP_FAIL;e=sendf(i,1,p,n);if(e!=ESP_OK)return e;size_t l;e=waittype(i,2,&l);if(e!=ESP_OK)return e;esphome_api_probe_result_t tmp={0};if(!esphome_api_codec_parse_hello(i->frame,l,out?out:&tmp)){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_MALFORMED;hardclose(i);return ESP_ERR_INVALID_RESPONSE;}i->hello_done=true;return ESP_OK;}
esp_err_t esphome_api_init(esphome_api_session_t*s,const esphome_api_config_t*c){if(!s||!c||!c->host)return ESP_ERR_INVALID_ARG;size_t h=strnlen(c->host,ESPHOME_API_MAX_HOST_LEN+1);if(!h||h>ESPHOME_API_MAX_HOST_LEN)return ESP_ERR_INVALID_ARG;if((c->noise_psk==NULL)!=(c->noise_psk_len==0))return ESP_ERR_INVALID_ARG;if(c->noise_psk&&c->noise_psk_len!=32)return ESP_ERR_INVALID_ARG;if(c->max_frame_bytes>ESPHOME_API_MAX_FRAME_BYTES)return ESP_ERR_INVALID_ARG;memset(s,0,sizeof(*s));impl_t*i=I(s);i->magic=MAGIC;i->sock=BADFD;i->timeout_ms=c->timeout_ms?c->timeout_ms:DEF_TO;i->port=c->port?c->port:ESPHOME_API_DEFAULT_PORT;i->max_frame=c->max_frame_bytes?c->max_frame_bytes:ESPHOME_API_MAX_FRAME_BYTES;memcpy(i->host,c->host,h);i->host[h]=0;i->noise_requested=c->noise_psk!=NULL;i->initialized=true;return ESP_OK;}
void esphome_api_deinit(esphome_api_session_t*s){if(!s)return;impl_t*i=I(s);if(valid(i))hardclose(i);memset(s,0,sizeof(*s));}
esp_err_t esphome_api_probe(esphome_api_session_t*s,esphome_api_probe_result_t*out){if(!s||!out)return ESP_ERR_INVALID_ARG;impl_t*i=I(s);if(!valid(i))return ESP_ERR_INVALID_STATE;memset(out,0,sizeof(*out));esp_err_t e=hello(i,out);if(e!=ESP_OK)return e;e=sendf(i,9,NULL,0);if(e!=ESP_OK)return e;size_t l;e=waittype(i,10,&l);if(e!=ESP_OK)return e;if(!esphome_api_codec_parse_device_info(i->frame,l,out)){i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_MALFORMED;hardclose(i);return ESP_ERR_INVALID_RESPONSE;}i->probed=true;return ESP_OK;}
esp_err_t esphome_api_entities(esphome_api_session_t*s,esphome_api_entity_list_t*out){if(!s||!out||(out->capacity&&!out->items))return ESP_ERR_INVALID_ARG;impl_t*i=I(s);if(!valid(i))return ESP_ERR_INVALID_STATE;esp_err_t e=hello(i,NULL);if(e!=ESP_OK)return e;out->count=out->total_seen=out->unsupported_seen=0;out->truncated=false;e=sendf(i,11,NULL,0);if(e!=ESP_OK)return e;for(size_t g=0;g<1024;g++){uint16_t t;size_t l;e=recvf(i,&t,&l,i->timeout_ms);if(e!=ESP_OK)return e;bool h;e=control(i,t,&h);if(e!=ESP_OK)return e;if(h)continue;if(t==19)return ESP_OK;esphome_api_entity_t ent;if(esphome_api_codec_parse_entity(t,i->frame,l,&ent)){out->total_seen++;if(out->count<out->capacity)out->items[out->count++]=ent;else out->truncated=true;}else out->unsupported_seen++;}i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_MALFORMED;hardclose(i);return ESP_ERR_INVALID_RESPONSE;}
esp_err_t esphome_api_subscribe(esphome_api_session_t*s,esphome_api_state_fn cb,void*u){if(!s||!cb)return ESP_ERR_INVALID_ARG;impl_t*i=I(s);if(!valid(i))return ESP_ERR_INVALID_STATE;esp_err_t e=hello(i,NULL);if(e!=ESP_OK)return e;e=sendf(i,20,NULL,0);if(e==ESP_OK){i->state_cb=cb;i->state_user=u;i->subscribed=true;}return e;}
esp_err_t esphome_api_poll(esphome_api_session_t*s,uint32_t timeout){if(!s)return ESP_ERR_INVALID_ARG;impl_t*i=I(s);if(!valid(i)||!i->connected||!i->subscribed)return ESP_ERR_INVALID_STATE;uint16_t t;size_t l;esp_err_t e=recvf(i,&t,&l,timeout);if(e!=ESP_OK)return e;bool h;e=control(i,t,&h);if(e!=ESP_OK||h)return e;esphome_api_state_t st;if(esphome_api_codec_parse_state(t,i->frame,l,&st)){i->state_cb(&st,i->state_user);return ESP_OK;}return ESP_OK;}
esp_err_t esphome_api_command(esphome_api_session_t*s,const esphome_api_command_t*c){if(!s||!c)return ESP_ERR_INVALID_ARG;impl_t*i=I(s);if(!valid(i))return ESP_ERR_INVALID_STATE;uint16_t t;size_t n;uint8_t p[256];if(!esphome_api_codec_command(c,&t,p,sizeof(p),&n))return ESP_ERR_INVALID_ARG;(void)t;(void)n;(void)p;i->protocol_error=ESPHOME_API_PROTOCOL_ERROR_AUTH_REQUIRED;return ESP_ERR_NOT_SUPPORTED;}
esp_err_t esphome_api_close(esphome_api_session_t*s){if(!s)return ESP_ERR_INVALID_ARG;impl_t*i=I(s);if(!valid(i))return ESP_ERR_INVALID_STATE;if(!i->connected)return ESP_OK;esp_err_t e=sendf(i,5,NULL,0);if(e==ESP_OK){uint16_t t;size_t l;esp_err_t r=recvf(i,&t,&l,i->timeout_ms);if(r==ESP_OK&&t!=6)r=ESP_ERR_INVALID_RESPONSE;if(r!=ESP_OK)e=r;}hardclose(i);return e;}
void esphome_api_cancel(esphome_api_session_t*s){if(!s)return;impl_t*i=I(s);if(valid(i))hardclose(i);} bool esphome_api_is_connected(const esphome_api_session_t*s){if(!s)return false;const impl_t*i=CI(s);return valid(i)&&i->connected;} esphome_api_protocol_error_t esphome_api_last_protocol_error(const esphome_api_session_t*s){if(!s)return ESPHOME_API_PROTOCOL_ERROR_NONE;const impl_t*i=CI(s);return i->magic==MAGIC?i->protocol_error:ESPHOME_API_PROTOCOL_ERROR_NONE;}
