#include "esphome_ble_gatt.h"
#include "private/esphome_ble_gatt_internal.h"
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/semphr.h"
#include "host/ble_gap.h"
#include "host/ble_gatt.h"
#include "host/ble_hs.h"
#include "host/ble_uuid.h"
#include "host/util/util.h"
#include "os/os_mbuf.h"
#define INVALID_CONN 0xFFFFu
#define NOTIFY_COPY_MAX 256u
typedef enum { WAIT_NONE=0,WAIT_CONNECT,WAIT_DISCONNECT,WAIT_GATT } wait_kind_t;
typedef struct { SemaphoreHandle_t done; void *owner; esphome_ble_gatt_backend_notify_fn notify; esphome_ble_gatt_db_t *db; uint8_t *read_out; size_t read_cap,*read_len; uint16_t conn_handle; int op_status; bool connected,characteristics_truncated; wait_kind_t wait_kind; } nimble_ctx_t;
_Static_assert(sizeof(nimble_ctx_t)<=ESPHOME_BLE_GATT_BACKEND_BYTES,"increase ESPHOME_BLE_GATT_BACKEND_BYTES");
static esp_err_t maprc(int rc){if(rc==0)return ESP_OK;switch(rc){case BLE_HS_ENOMEM:return ESP_ERR_NO_MEM;case BLE_HS_ETIMEOUT:case BLE_HS_ETIMEOUT_HCI:return ESP_ERR_TIMEOUT;case BLE_HS_EINVAL:return ESP_ERR_INVALID_ARG;case BLE_HS_ENOTCONN:return ESP_ERR_INVALID_STATE;case BLE_HS_EALREADY:return ESP_ERR_INVALID_STATE;case BLE_HS_EBUSY:return ESP_ERR_INVALID_STATE;default:return ESP_FAIL;}}
static void drain(nimble_ctx_t*c){while(xSemaphoreTake(c->done,0)==pdTRUE){}}
static esp_err_t waitdone(nimble_ctx_t*c,uint32_t ms,int*native){TickType_t ticks=pdMS_TO_TICKS(ms);if(ticks==0)ticks=1;if(xSemaphoreTake(c->done,ticks)!=pdTRUE){c->wait_kind=WAIT_NONE;if(native)*native=BLE_HS_ETIMEOUT;return ESP_ERR_TIMEOUT;}c->wait_kind=WAIT_NONE;if(native)*native=c->op_status;return maprc(c->op_status);}
static void uuidcopy(esphome_ble_uuid_t*out,const ble_uuid_t*u){memset(out,0,sizeof(*out));if(!u)return;const ble_uuid_any_t*a=(const void*)u;if(u->type==BLE_UUID_TYPE_16){out->width=ESPHOME_BLE_UUID16;uint16_t v=a->u16.value;out->value[0]=(uint8_t)v;out->value[1]=(uint8_t)(v>>8);}else if(u->type==BLE_UUID_TYPE_32){out->width=ESPHOME_BLE_UUID32;uint32_t v=a->u32.value;out->value[0]=(uint8_t)v;out->value[1]=(uint8_t)(v>>8);out->value[2]=(uint8_t)(v>>16);out->value[3]=(uint8_t)(v>>24);}else if(u->type==BLE_UUID_TYPE_128){out->width=ESPHOME_BLE_UUID128;memcpy(out->value,a->u128.value,16);}}
static int gapcb(struct ble_gap_event*e,void*arg){nimble_ctx_t*c=arg;if(!e||!c)return 0;switch(e->type){case BLE_GAP_EVENT_CONNECT:if(c->wait_kind!=WAIT_CONNECT){if(e->connect.status==0)(void)ble_gap_terminate(e->connect.conn_handle,BLE_ERR_REM_USER_CONN_TERM);c->connected=false;c->conn_handle=INVALID_CONN;break;}c->op_status=e->connect.status;if(e->connect.status==0){c->conn_handle=e->connect.conn_handle;c->connected=true;}else{c->conn_handle=INVALID_CONN;c->connected=false;}xSemaphoreGive(c->done);break;case BLE_GAP_EVENT_DISCONNECT:c->connected=false;c->conn_handle=INVALID_CONN;c->op_status=(c->wait_kind==WAIT_DISCONNECT)?0:BLE_HS_ENOTCONN;if(c->wait_kind!=WAIT_NONE)xSemaphoreGive(c->done);break;case BLE_GAP_EVENT_NOTIFY_RX:if(c->notify){size_t total=OS_MBUF_PKTLEN(e->notify_rx.om);uint8_t b[NOTIFY_COPY_MAX];uint16_t copied=0;size_t take=total>sizeof(b)?sizeof(b):total;if(ble_hs_mbuf_to_flat(e->notify_rx.om,b,take,&copied)==0)c->notify(c->owner,e->notify_rx.attr_handle,b,copied,total>copied);}break;default:break;}return 0;}
static esp_err_t bi(void*ctx,void*owner,esphome_ble_gatt_backend_notify_fn n,int*native){nimble_ctx_t*c=ctx;memset(c,0,sizeof(*c));c->done=xSemaphoreCreateBinary();if(!c->done)return ESP_ERR_NO_MEM;c->owner=owner;c->notify=n;c->conn_handle=INVALID_CONN;if(native)*native=0;return ESP_OK;}
static void bd(void*ctx){nimble_ctx_t*c=ctx;if(c->done)vSemaphoreDelete(c->done);memset(c,0,sizeof(*c));}
static esp_err_t bc(void*ctx,const esphome_ble_peer_t*p,uint32_t ms,int*native){nimble_ctx_t*c=ctx;uint8_t own=0;int rc=ble_hs_id_infer_auto(0,&own);if(rc){if(native)*native=rc;return maprc(rc);}ble_addr_t a={.type=p->address_type};for(size_t k=0;k<6;k++)a.val[k]=p->address[5-k];drain(c);c->op_status=BLE_HS_ETIMEOUT;c->wait_kind=WAIT_CONNECT;rc=ble_gap_connect(own,&a,(int32_t)ms,NULL,gapcb,c);if(rc){c->wait_kind=WAIT_NONE;if(native)*native=rc;return maprc(rc);}esp_err_t e=waitdone(c,ms+250u,native);if(e==ESP_ERR_TIMEOUT){(void)ble_gap_conn_cancel();c->connected=false;c->conn_handle=INVALID_CONN;}return e;}
static int svccb(uint16_t h,const struct ble_gatt_error*er,const struct ble_gatt_svc*s,void*arg){(void)h;nimble_ctx_t*c=arg;if(c->wait_kind!=WAIT_GATT||!c->db)return 0;if(er->status==0&&s){if(c->db->service_count<c->db->service_capacity){esphome_ble_gatt_service_t*d=&c->db->services[c->db->service_count++];memset(d,0,sizeof(*d));uuidcopy(&d->uuid,&s->uuid.u);d->start_handle=s->start_handle;d->end_handle=s->end_handle;}else c->db->truncated=true;return 0;}c->op_status=er->status==BLE_HS_EDONE?0:er->status;xSemaphoreGive(c->done);return 0;}
static int chrcb(uint16_t h,const struct ble_gatt_error*er,const struct ble_gatt_chr*x,void*arg){(void)h;nimble_ctx_t*c=arg;if(c->wait_kind!=WAIT_GATT||!c->db)return 0;if(er->status==0&&x){if(c->db->characteristic_count<c->db->characteristic_capacity){esphome_ble_gatt_characteristic_t*d=&c->db->characteristics[c->db->characteristic_count++];memset(d,0,sizeof(*d));uuidcopy(&d->uuid,&x->uuid.u);d->definition_handle=x->def_handle;d->value_handle=x->val_handle;d->properties=x->properties;}else{c->db->truncated=true;c->characteristics_truncated=true;}return 0;}c->op_status=er->status==BLE_HS_EDONE?0:er->status;xSemaphoreGive(c->done);return 0;}
static int dsccb(uint16_t h,const struct ble_gatt_error*er,uint16_t vh,const struct ble_gatt_dsc*x,void*arg){(void)h;(void)vh;nimble_ctx_t*c=arg;if(c->wait_kind!=WAIT_GATT||!c->db)return 0;if(er->status==0&&x){if(c->db->descriptor_count<c->db->descriptor_capacity){esphome_ble_gatt_descriptor_t*d=&c->db->descriptors[c->db->descriptor_count++];memset(d,0,sizeof(*d));uuidcopy(&d->uuid,&x->uuid.u);d->handle=x->handle;}else c->db->truncated=true;return 0;}c->op_status=er->status==BLE_HS_EDONE?0:er->status;xSemaphoreGive(c->done);return 0;}
static esp_err_t sw(nimble_ctx_t*c,int rc,uint32_t ms,int*native){if(rc){c->wait_kind=WAIT_NONE;if(native)*native=rc;return maprc(rc);}return waitdone(c,ms,native);}
static esp_err_t bdiscover(void*ctx,esphome_ble_gatt_db_t*db,uint32_t ms,int*native){nimble_ctx_t*c=ctx;c->db=db;c->characteristics_truncated=false;drain(c);c->op_status=BLE_HS_ETIMEOUT;c->wait_kind=WAIT_GATT;esp_err_t e=sw(c,ble_gattc_disc_all_svcs(c->conn_handle,svccb,c),ms,native);if(e!=ESP_OK)goto out;for(uint16_t s=0;s<db->service_count;s++){esphome_ble_gatt_service_t*svc=&db->services[s];svc->first_characteristic=db->characteristic_count;drain(c);c->op_status=BLE_HS_ETIMEOUT;c->wait_kind=WAIT_GATT;e=sw(c,ble_gattc_disc_all_chrs(c->conn_handle,svc->start_handle,svc->end_handle,chrcb,c),ms,native);if(e!=ESP_OK)goto out;svc->characteristic_count=(uint16_t)(db->characteristic_count-svc->first_characteristic);for(uint16_t j=0;j<svc->characteristic_count;j++){uint16_t idx=(uint16_t)(svc->first_characteristic+j);esphome_ble_gatt_characteristic_t*ch=&db->characteristics[idx];ch->end_handle=(j+1<svc->characteristic_count)?(uint16_t)(db->characteristics[idx+1].definition_handle-1u):svc->end_handle;}}
if(c->characteristics_truncated){for(uint16_t k=0;k<db->characteristic_count;k++){db->characteristics[k].first_descriptor=0;db->characteristics[k].descriptor_count=0;db->characteristics[k].end_handle=db->characteristics[k].value_handle;}goto out;}
for(uint16_t k=0;k<db->characteristic_count;k++){esphome_ble_gatt_characteristic_t*ch=&db->characteristics[k];ch->first_descriptor=db->descriptor_count;if(ch->end_handle<=ch->value_handle)continue;drain(c);c->op_status=BLE_HS_ETIMEOUT;c->wait_kind=WAIT_GATT;e=sw(c,ble_gattc_disc_all_dscs(c->conn_handle,ch->value_handle,ch->end_handle,dsccb,c),ms,native);if(e!=ESP_OK)goto out;ch->descriptor_count=(uint16_t)(db->descriptor_count-ch->first_descriptor);}out:c->db=NULL;return e;}
static int readcb(uint16_t h,const struct ble_gatt_error*er,struct ble_gatt_attr*a,void*arg){(void)h;nimble_ctx_t*c=arg;if(c->wait_kind!=WAIT_GATT||!c->read_len)return 0;c->op_status=er->status;if(er->status==0&&a&&a->om){size_t total=OS_MBUF_PKTLEN(a->om);*c->read_len=total;if(total>c->read_cap)c->op_status=BLE_HS_ENOMEM;else if(total){uint16_t copied=0;int rc=ble_hs_mbuf_to_flat(a->om,c->read_out,total,&copied);if(rc||copied!=total)c->op_status=rc?rc:BLE_HS_EUNKNOWN;}}xSemaphoreGive(c->done);return 0;}
static esp_err_t br(void*ctx,uint16_t h,uint8_t*out,size_t cap,size_t*len,uint32_t ms,int*native){nimble_ctx_t*c=ctx;c->read_out=out;c->read_cap=cap;c->read_len=len;drain(c);c->op_status=BLE_HS_ETIMEOUT;c->wait_kind=WAIT_GATT;esp_err_t e=sw(c,ble_gattc_read(c->conn_handle,h,readcb,c),ms,native);if(e==ESP_ERR_NO_MEM&&*len>cap)e=ESP_ERR_INVALID_SIZE;c->read_out=NULL;c->read_len=NULL;c->read_cap=0;return e;}
static int writecb(uint16_t h,const struct ble_gatt_error*er,struct ble_gatt_attr*a,void*arg){(void)h;(void)a;nimble_ctx_t*c=arg;if(c->wait_kind!=WAIT_GATT)return 0;c->op_status=er->status;xSemaphoreGive(c->done);return 0;}
static esp_err_t bw(void*ctx,uint16_t h,const uint8_t*d,size_t n,bool resp,uint32_t ms,int*native){nimble_ctx_t*c=ctx;if(!resp){int rc=ble_gattc_write_no_rsp_flat(c->conn_handle,h,d,(uint16_t)n);if(native)*native=rc;return maprc(rc);}drain(c);c->op_status=BLE_HS_ETIMEOUT;c->wait_kind=WAIT_GATT;return sw(c,ble_gattc_write_flat(c->conn_handle,h,d,(uint16_t)n,writecb,c),ms,native);}
static esp_err_t bn(void*ctx,uint16_t h,bool en,bool ind,uint32_t ms,int*native){uint8_t v[2]={0,0};if(en)v[0]=ind?2:1;return bw(ctx,h,v,sizeof(v),true,ms,native);}
static esp_err_t bdis(void*ctx,uint32_t ms,int*native){nimble_ctx_t*c=ctx;if(!c->connected||c->conn_handle==INVALID_CONN)return ESP_OK;drain(c);c->op_status=BLE_HS_ETIMEOUT;c->wait_kind=WAIT_DISCONNECT;int rc=ble_gap_terminate(c->conn_handle,BLE_ERR_REM_USER_CONN_TERM);if(rc){c->wait_kind=WAIT_NONE;if(rc==BLE_HS_ENOTCONN){c->connected=false;c->conn_handle=INVALID_CONN;return ESP_OK;}if(native)*native=rc;return maprc(rc);}esp_err_t e=waitdone(c,ms,native);if(e==ESP_OK){c->connected=false;c->conn_handle=INVALID_CONN;}return e;}
static esp_err_t bcan(void*ctx,uint32_t ms,int*native){nimble_ctx_t*c=ctx;if(!c->connected||c->conn_handle==INVALID_CONN){int rc=ble_gap_conn_cancel();if(rc==0||rc==BLE_HS_EALREADY)return ESP_OK;if(native)*native=rc;return maprc(rc);}return bdis(ctx,ms,native);}
static bool bis(const void*ctx){return ((const nimble_ctx_t*)ctx)->connected;}
const esphome_ble_gatt_backend_ops_t esphome_ble_gatt_nimble_backend={.init=bi,.deinit=bd,.connect=bc,.discover=bdiscover,.read=br,.write=bw,.set_notify=bn,.cancel=bcan,.disconnect=bdis,.connected=bis};
