idf_component_register(
    SRCS
        "main.c"
        "app_ops.c"
        "app_diag_protocol.c"
        "app_scan.c"
        "app_str.c"
        "device_db_format.c"
        "app_recognition.c"
        "app_device_db.c"
        "app_device.c"
        "app_wifi.c"
        "app_scan_native.c"
        "app_runtime.c"
        "app_diag_console.c"
    INCLUDE_DIRS "." "include"
    REQUIRES
        board
        lvgl_port
        lvgl
        freertos
        esp_timer
        esp_driver_uart
        esp_app_format
        esp_wifi
        esp_event
        esp_netif
        nvs_flash
        lwip
        ha_core
        ha_discovery_l2
        esphome_l2
        theengs_l2
        zha_l2
        zigpy_l2
        openthread_l2
        kismet_l2
        nmap_l2
        wireshark_l2
)
