#include <assert.h>
#include <pthread.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <unistd.h>
#include "esphome_api.h"
#include "private/esphome_api_codec.h"
typedef struct{int listen_fd;int mode;} server_arg_t;
static bool allr(int fd,uint8_t*p,size_t n){while(n){ssize_t r=recv(fd,p,n,0);if(r<=0)return false;p+=(size_t)r;n-=(size_t)r;}return true;}static bool allw(int fd,const uint8_t*p,size_t n){while(n){ssize_t r=send(fd,p,n,0);if(r<=0)return false;p+=(size_t)r;n-=(size_t)r;}return true;}
static bool readv(int fd,uint32_t*out){uint32_t v=0;unsigned sh=0;for(int i=0;i<4;i++){uint8_t b;if(!allr(fd,&b,1))return false;v|=(uint32_t)(b&0x7f)<<sh;if(!(b&0x80)){*out=v;return true;}sh+=7;}return false;}static size_t encv(uint32_t v,uint8_t*b){size_t n=0;do{uint8_t x=v&0x7f;v>>=7;if(v)x|=0x80;b[n++]=x;}while(v);return n;}
static bool recv_frame(int fd,uint16_t*t,uint8_t*p,size_t cap,size_t*n){uint8_t z;if(!allr(fd,&z,1)||z!=0)return false;uint32_t len,type;if(!readv(fd,&len)||!readv(fd,&type)||len>cap)return false;if(len&&!allr(fd,p,len))return false;*t=(uint16_t)type;*n=len;return true;}static bool send_frame(int fd,uint16_t t,const uint8_t*p,size_t n){uint8_t h[12];size_t k=0;h[k++]=0;k+=encv((uint32_t)n,h+k);k+=encv(t,h+k);return allw(fd,h,k)&&(!n||allw(fd,p,n));}
static void *server(void*vp){server_arg_t*a=vp;int fd=accept(a->listen_fd,NULL,NULL);assert(fd>=0);if(a->mode==1){uint8_t tmp[64];(void)recv(fd,tmp,sizeof(tmp),0);uint8_t one=1;assert(allw(fd,&one,1));close(fd);return NULL;}uint8_t p[512];size_t n;uint16_t t;assert(recv_frame(fd,&t,p,sizeof(p),&n)&&t==1);
esphome_pb_writer_t w;esphome_pb_writer_init(&w,p,sizeof(p));esphome_pb_put_varint(&w,1,1);esphome_pb_put_varint(&w,2,15);esphome_pb_put_string(&w,3,"ESPHome 2026.8.0",32);esphome_pb_put_string(&w,4,"test-node",31);assert(send_frame(fd,2,p,w.len));
assert(recv_frame(fd,&t,p,sizeof(p),&n)&&t==9);esphome_pb_writer_init(&w,p,sizeof(p));esphome_pb_put_string(&w,2,"test-node",31);esphome_pb_put_string(&w,3,"AA:BB:CC:DD:EE:FF",17);esphome_pb_put_string(&w,4,"2026.8.0",32);esphome_pb_put_string(&w,6,"esp32-c6",127);esphome_pb_put_string(&w,12,"Espressif",20);esphome_pb_put_string(&w,13,"Kitchen Node",120);assert(send_frame(fd,10,p,w.len));
assert(recv_frame(fd,&t,p,sizeof(p),&n)&&t==11);assert(send_frame(fd,36,NULL,0));esphome_pb_writer_init(&w,p,sizeof(p));esphome_pb_put_string(&w,1,"relay",120);esphome_pb_put_fixed32(&w,2,0x11111111);esphome_pb_put_string(&w,3,"Relay",120);esphome_pb_put_string(&w,9,"outlet",47);assert(send_frame(fd,17,p,w.len));esphome_pb_writer_init(&w,p,sizeof(p));esphome_pb_put_string(&w,1,"temp",120);esphome_pb_put_fixed32(&w,2,0x22222222);esphome_pb_put_string(&w,3,"Temperature",120);esphome_pb_put_string(&w,6,"C",63);assert(send_frame(fd,16,p,w.len));assert(send_frame(fd,13,NULL,0));assert(send_frame(fd,19,NULL,0));
assert(recv_frame(fd,&t,p,sizeof(p),&n)&&t==20);esphome_pb_writer_init(&w,p,sizeof(p));esphome_pb_put_fixed32(&w,1,0x11111111);esphome_pb_put_bool(&w,2,true);assert(send_frame(fd,26,p,w.len));
assert(recv_frame(fd,&t,p,sizeof(p),&n)&&t==5);assert(send_frame(fd,6,NULL,0));close(fd);return NULL;}
static uint16_t start_server(pthread_t*th,server_arg_t*a,int mode){a->listen_fd=socket(AF_INET,SOCK_STREAM,0);assert(a->listen_fd>=0);int yes=1;setsockopt(a->listen_fd,SOL_SOCKET,SO_REUSEADDR,&yes,sizeof(yes));struct sockaddr_in sa={.sin_family=AF_INET,.sin_addr.s_addr=htonl(INADDR_LOOPBACK),.sin_port=0};assert(bind(a->listen_fd,(void*)&sa,sizeof(sa))==0&&listen(a->listen_fd,1)==0);socklen_t sl=sizeof(sa);assert(getsockname(a->listen_fd,(void*)&sa,&sl)==0);a->mode=mode;assert(pthread_create(th,NULL,server,a)==0);return ntohs(sa.sin_port);}static int got_state;static void scb(const esphome_api_state_t*s,void*u){(void)u;assert(s->kind==ESPHOME_API_ENTITY_SWITCH&&s->key==0x11111111&&s->value.boolean);got_state++;}
int main(void){pthread_t th;server_arg_t a;uint16_t port=start_server(&th,&a,0);esphome_api_session_t s;esphome_api_config_t c={.host="127.0.0.1",.port=port,.timeout_ms=1000,.max_frame_bytes=512};assert(esphome_api_init(&s,&c)==ESP_OK);esphome_api_probe_result_t pr;assert(esphome_api_probe(&s,&pr)==ESP_OK&&pr.api_version_minor==15&&!strcmp(pr.name,"test-node")&&!strcmp(pr.model,"esp32-c6"));esphome_api_entity_t item[1];esphome_api_entity_list_t list={.items=item,.capacity=1};assert(esphome_api_entities(&s,&list)==ESP_OK&&list.count==1&&list.total_seen==2&&list.unsupported_seen==1&&list.truncated&&item[0].kind==ESPHOME_API_ENTITY_SWITCH);assert(esphome_api_subscribe(&s,scb,NULL)==ESP_OK);assert(esphome_api_poll(&s,1000)==ESP_OK&&got_state==1);esphome_api_command_t cmd={.kind=ESPHOME_API_COMMAND_SWITCH,.key=0x11111111,.value.switch_.state=false};assert(esphome_api_command(&s,&cmd)==ESP_ERR_NOT_SUPPORTED);assert(esphome_api_last_protocol_error(&s)==ESPHOME_API_PROTOCOL_ERROR_AUTH_REQUIRED);assert(esphome_api_close(&s)==ESP_OK&&!esphome_api_is_connected(&s));esphome_api_deinit(&s);pthread_join(th,NULL);close(a.listen_fd);
port=start_server(&th,&a,1);c.port=port;assert(esphome_api_init(&s,&c)==ESP_OK);assert(esphome_api_probe(&s,&pr)==ESP_ERR_NOT_SUPPORTED);assert(esphome_api_last_protocol_error(&s)==ESPHOME_API_PROTOCOL_ERROR_ENCRYPTION_REQUIRED);esphome_api_deinit(&s);pthread_join(th,NULL);close(a.listen_fd);
uint8_t key[32]={0};c.port=6553;c.noise_psk=key;c.noise_psk_len=sizeof(key);assert(esphome_api_init(&s,&c)==ESP_OK);assert(esphome_api_probe(&s,&pr)==ESP_ERR_NOT_SUPPORTED);assert(esphome_api_last_protocol_error(&s)==ESPHOME_API_PROTOCOL_ERROR_NOISE_NOT_SUPPORTED);esphome_api_deinit(&s);puts("api client tests: ok");return 0;}
