/* Noise_NNpsk0_25519_ChaChaPoly_SHA256 conformance and interoperability tests.
 *
 * Two independent oracles are used:
 *   1. Pinned fixtures generated by tools/reference/noise_nnpsk0_reference.py,
 *      which re-implements the handshake in Python on top of hashlib and the
 *      `cryptography` package. Byte-for-byte agreement with those fixtures is
 *      an external check, not a self-consistency check.
 *   2. A minimal responder written directly against the Noise specification
 *      inside this file, used to drive the initiator through a full exchange
 *      with freshly generated ephemeral keys.
 */
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "esphome_noise.h"
#include "esphome_noise_crypto.h"
/* The shared responder that test_api_client also uses. It is a second implementation of
 * the same state machine, so putting it against the firmware's initiator here is a
 * cross-implementation check rather than a self-consistency one. */
#include "noise_test_responder.h"

static int failures;

#define CHECK(cond, ...)                                                                 \
    do {                                                                                 \
        if (!(cond)) {                                                                   \
            failures++;                                                                  \
            printf("FAIL %s:%d: ", __func__, __LINE__);                                  \
            printf(__VA_ARGS__);                                                         \
            printf("\n");                                                                \
        }                                                                                \
    } while (0)

static bool same(const uint8_t *a, const uint8_t *b, size_t n)
{
    return memcmp(a, b, n) == 0;
}

/* ------------------------------------------------------------------ */
/* Pinned fixtures from tools/reference/noise_nnpsk0_reference.py       */
/* ------------------------------------------------------------------ */

static const uint8_t PROLOGUE[12] = {0x4e, 0x6f, 0x69, 0x73, 0x65, 0x41, 0x50, 0x49, 0x49, 0x6e, 0x69, 0x74};
static const uint8_t PSK[32] = {0};
static const uint8_t CLIENT_ENTROPY[32] = {0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c,
                                          0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18,
                                          0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20};
static const uint8_t CLIENT_PUB[32] = {0x07, 0xa3, 0x7c, 0xbc, 0x14, 0x20, 0x93, 0xc8, 0xb7, 0x55, 0xdc, 0x1b,
                                       0x10, 0xe8, 0x6c, 0xb4, 0x26, 0x37, 0x4a, 0xd1, 0x6a, 0xa8, 0x53, 0xed,
                                       0x0b, 0xdf, 0xc0, 0xb2, 0xb8, 0x6d, 0x1c, 0x7c};
static const uint8_t SERVER_PUB[32] = {0x58, 0x69, 0xaf, 0xf4, 0x50, 0x54, 0x97, 0x32, 0xcb, 0xaa, 0xed, 0x5e,
                                       0x5d, 0xf9, 0xb3, 0x0a, 0x6d, 0xa3, 0x1c, 0xb0, 0xe5, 0x74, 0x2b, 0xad,
                                       0x5a, 0xd4, 0xa1, 0xa7, 0x68, 0xf1, 0xa6, 0x7b};
static const uint8_t HANDSHAKE_HASH[32] = {0xde, 0x50, 0x78, 0x70, 0x91, 0x82, 0x3a, 0x4e, 0x6e, 0x0e, 0xb5,
                                           0xb7, 0x93, 0xf6, 0x16, 0xd0, 0x29, 0x7e, 0x54, 0xe9, 0x42, 0xbf,
                                           0x00, 0xb6, 0x58, 0xfa, 0x69, 0x27, 0x6f, 0x86, 0xc0, 0x1e};
static const uint8_t MSG1[48] = {0x07, 0xa3, 0x7c, 0xbc, 0x14, 0x20, 0x93, 0xc8, 0xb7, 0x55, 0xdc, 0x1b, 0x10, 0xe8,
                                 0x6c, 0xb4, 0x26, 0x37, 0x4a, 0xd1, 0x6a, 0xa8, 0x53, 0xed, 0x0b, 0xdf, 0xc0, 0xb2,
                                 0xb8, 0x6d, 0x1c, 0x7c, 0x42, 0x0c, 0x65, 0x70, 0x65, 0x20, 0xd6, 0xf8, 0xd4, 0x8d,
                                 0xe7, 0x89, 0xa5, 0x57, 0x7c, 0x73};
static const uint8_t MSG2[48] = {0x58, 0x69, 0xaf, 0xf4, 0x50, 0x54, 0x97, 0x32, 0xcb, 0xaa, 0xed, 0x5e, 0x5d, 0xf9,
                                 0xb3, 0x0a, 0x6d, 0xa3, 0x1c, 0xb0, 0xe5, 0x74, 0x2b, 0xad, 0x5a, 0xd4, 0xa1, 0xa7,
                                 0x68, 0xf1, 0xa6, 0x7b, 0xe5, 0x2d, 0x50, 0x7f, 0x7d, 0x64, 0xf6, 0x11, 0xc9, 0x54,
                                 0x00, 0x60, 0x07, 0x2a, 0xb9, 0x5c};
static const uint8_t SEND_KEY[32] = {0xcd, 0x90, 0x67, 0xa8, 0x0a, 0x2b, 0x24, 0xde, 0x88, 0xfe, 0x47, 0xf3,
                                     0xc6, 0xff, 0x30, 0x1b, 0x1b, 0xa2, 0xa4, 0xbd, 0xd1, 0x52, 0x90, 0x99,
                                     0xd2, 0xd4, 0x20, 0x9d, 0xcb, 0x83, 0x3e, 0x71};
static const uint8_t RECV_KEY[32] = {0x4d, 0xa3, 0x8b, 0x2c, 0x27, 0x0c, 0x07, 0x77, 0xff, 0xd8, 0x5c, 0xce,
                                     0xeb, 0x36, 0xca, 0xce, 0x75, 0x7d, 0x54, 0xb0, 0x28, 0xe2, 0x4d, 0x58,
                                     0x2f, 0xec, 0x08, 0x1e, 0x84, 0xa2, 0x09, 0xc9};
static const uint8_t SENT_0[23] = {0x01, 0x00, 0x14, 0xe1, 0xfd, 0x85, 0x0a, 0xdb, 0x90, 0xff, 0x9f, 0xd6, 0x67, 0xfa, 0x4f,
                                   0x17, 0xdc, 0x34, 0xf8, 0xbe, 0xfa, 0xd4, 0xe8};
static const uint8_t SENT_1[23] = {0x01, 0x00, 0x14, 0xbc, 0x36, 0x12, 0x1f, 0xcb, 0x7e, 0x80, 0xec, 0x7b, 0xb3, 0x51, 0x18,
                                   0xcf, 0x37, 0x65, 0x49, 0x1d, 0xd3, 0x26, 0x00};
static const uint8_t SENT_2[23] = {0x01, 0x00, 0x14, 0xbb, 0x06, 0x59, 0x8d, 0x42, 0xfa, 0x13, 0xcc, 0xd0, 0x54, 0xe0, 0x8e,
                                   0x09, 0x62, 0xf7, 0x23, 0xe1, 0x67, 0x66, 0x6a};
static const uint8_t SENT_3[23] = {0x01, 0x00, 0x14, 0x31, 0xcc, 0x98, 0x48, 0x71, 0x96, 0xaa, 0x19, 0x27, 0xb8, 0xf3, 0x03,
                                   0x98, 0x3f, 0x6a, 0x5e, 0x8b, 0x17, 0x33, 0xb5};
static const uint8_t SENT_4[29] = {0x01, 0x00, 0x1a, 0xe7, 0x3a, 0x83, 0xed, 0x66, 0x0f, 0x45, 0x19, 0xf4, 0xe8, 0x09, 0x3d,
                                   0x3e, 0x85, 0x4d, 0xbc, 0x30, 0xe1, 0x93, 0xcd, 0x0d, 0xe9, 0x0f, 0x41, 0x84, 0x45};
static const uint8_t RECVD_0[25] = {0x01, 0x00, 0x16, 0x59, 0xd4, 0xce, 0x7f, 0x93, 0x8d, 0x2e, 0x4c, 0xc5, 0x2e, 0x91, 0xac,
                                    0x4f, 0x3a, 0xb1, 0xf3, 0x56, 0xa8, 0x63, 0xef, 0x44, 0x99};
static const uint8_t RECVD_1[29] = {0x01, 0x00, 0x1a, 0x16, 0x66, 0xff, 0xb8, 0xa9, 0x3c, 0x3e, 0x03, 0x74, 0x95, 0x72, 0x07,
                                    0x11, 0x61, 0xa9, 0x11, 0x4f, 0x29, 0x23, 0x5d, 0x61, 0xe2, 0xb1, 0x7f, 0xbd, 0xc6};
static const uint8_t SERVER_FRAME[20] = {0x59, 0xd0, 0xce, 0x7d, 0xd8, 0x47, 0xa9, 0x3e, 0x23, 0xd0,
                                         0x46, 0x83, 0x9d, 0xdd, 0x88, 0x71, 0xa0, 0xda, 0x07, 0x16};

/* ------------------------------------------------------------------ */
/* helpers                                                             */
/* ------------------------------------------------------------------ */

static void deterministic_entropy(void *user, uint8_t *out, size_t len)
{
    uint32_t *counter = (uint32_t *)user;
    for (size_t i = 0; i < len; i++) {
        (*counter)++;
        out[i] = (uint8_t)((*counter * 2654435761u) >> 13);
    }
}

static void clampi(uint8_t k[32])
{
    k[0] &= 248u;
    k[31] &= 127u;
    k[31] |= 64u;
}

static void make_keypair(uint32_t *counter, uint8_t priv[32], uint8_t pub[32])
{
    deterministic_entropy(counter, priv, 32);
    clampi(priv);
    noise_x25519_public_key(pub, priv);
}

/* ------------------------------------------------------------------ */
/* pinned conformance                                                  */
/* ------------------------------------------------------------------ */

static void test_pinned_handshake(void)
{
    esphome_noise_handshake_t hs;
    esphome_noise_cipherstate_t send, recv;
    uint8_t out[64];
    size_t out_len = 0;
    uint32_t counter = 0;

    CHECK(esphome_noise_initiator_init(&hs, PSK, sizeof(PSK), PROLOGUE, sizeof(PROLOGUE),
                                       deterministic_entropy, &counter) == ESPHOME_NOISE_OK,
          "init failed");
    CHECK(esphome_noise_step(&hs) == ESPHOME_NOISE_STEP_WRITE, "expected WRITE first");
    CHECK(esphome_noise_set_fixed_ephemeral(&hs, CLIENT_ENTROPY) == ESPHOME_NOISE_OK,
          "fixed ephemeral rejected");

    memset(out, 0xaa, sizeof(out));
    CHECK(esphome_noise_write_message(&hs, out, sizeof(out), &out_len) == ESPHOME_NOISE_OK,
          "write_message failed");
    CHECK(out_len == 48u, "handshake message 1 length is %u, expected 48", (unsigned)out_len);
    CHECK(same(out, MSG1, sizeof(MSG1)), "handshake message 1 does not match the reference vector");
    CHECK(same(out, CLIENT_PUB, 32), "message 1 does not start with the client ephemeral public key");
    CHECK(counter == 0u, "fixed ephemeral was ignored, entropy was consumed");
    CHECK(esphome_noise_step(&hs) == ESPHOME_NOISE_STEP_READ, "expected READ second");

    CHECK(esphome_noise_read_message(&hs, MSG2, sizeof(MSG2)) == ESPHOME_NOISE_OK,
          "read_message failed on the reference vector");
    CHECK(same(MSG2, SERVER_PUB, 32), "reference message 2 does not start with the server ephemeral key");
    CHECK(esphome_noise_step(&hs) == ESPHOME_NOISE_STEP_DONE, "handshake did not complete");

    CHECK(esphome_noise_split(&hs, &send, &recv) == ESPHOME_NOISE_OK, "split failed");
    CHECK(same(send.key, SEND_KEY, 32), "split send key does not match the reference vector");
    CHECK(same(recv.key, RECV_KEY, 32), "split recv key does not match the reference vector");
    CHECK(send.nonce == 0u && recv.nonce == 0u, "transport nonces must start at zero");

    {
        uint8_t hh[32];
        CHECK(esphome_noise_handshake_hash(&hs, hh) == ESPHOME_NOISE_OK, "handshake hash failed");
        CHECK(same(hh, HANDSHAKE_HASH, 32), "handshake hash does not match the reference vector");
    }

    /* Transport: ESPHome HelloRequest is type 1 with an empty body. */
    {
        const uint8_t plaintext[4] = {0x00, 0x01, 0x00, 0x00};
        CHECK(esphome_noise_encrypt(&send, NULL, 0u, plaintext, sizeof(plaintext), out, sizeof(out),
                                    &out_len) == ESPHOME_NOISE_OK,
              "transport encrypt failed");
        CHECK(out_len == 20u, "transport frame length is %u, expected 20", (unsigned)out_len);
        CHECK(same(out, SENT_0 + 3u, sizeof(SENT_0) - 3u),
              "transport frame does not match the reference vector");
        CHECK(send.nonce == 1u, "send nonce did not advance exactly once");
    }
    {
        uint8_t plain[16];
        CHECK(esphome_noise_decrypt(&recv, NULL, 0u, SERVER_FRAME, sizeof(SERVER_FRAME), plain,
                                    sizeof(plain), &out_len) == ESPHOME_NOISE_OK,
              "transport decrypt failed on the reference frame");
        CHECK(out_len == 4u && plain[0] == 0x00 && plain[1] == 0x06 && plain[2] == 0x00 &&
                  plain[3] == 0x00,
              "decrypted server frame has the wrong contents");
        CHECK(recv.nonce == 1u, "recv nonce did not advance exactly once");
    }
}

static void test_pinned_wrong_psk_is_rejected(void)
{
    esphome_noise_handshake_t hs;
    uint8_t psk[32];
    uint8_t out[64];
    size_t out_len = 0;
    uint32_t counter = 0;

    memset(psk, 0, sizeof(psk));
    psk[31] = 0x01;
    CHECK(esphome_noise_initiator_init(&hs, psk, sizeof(psk), PROLOGUE, sizeof(PROLOGUE),
                                       deterministic_entropy, &counter) == ESPHOME_NOISE_OK,
          "init failed");
    CHECK(esphome_noise_set_fixed_ephemeral(&hs, CLIENT_ENTROPY) == ESPHOME_NOISE_OK, "fixed rejected");
    CHECK(esphome_noise_write_message(&hs, out, sizeof(out), &out_len) == ESPHOME_NOISE_OK, "write failed");
    CHECK(!same(out, MSG1, sizeof(MSG1)), "a different PSK produced the same first message");
    CHECK(esphome_noise_read_message(&hs, MSG2, sizeof(MSG2)) == ESPHOME_NOISE_ERR_AUTH_FAILED,
          "wrong PSK was not rejected");
    CHECK(esphome_noise_step(&hs) == ESPHOME_NOISE_STEP_FAILED, "failed handshake is not terminal");
}

static void test_tampered_handshake_message_is_rejected(void)
{
    esphome_noise_handshake_t hs;
    uint8_t msg[48];
    uint8_t out[64];
    size_t out_len = 0;
    uint32_t counter = 0;

    for (unsigned bit = 0; bit < 8u; bit++) {
        memcpy(msg, MSG2, sizeof(msg));
        msg[40u + bit / 8u] ^= (uint8_t)(1u << (bit % 8u)); /* inside the AEAD tag */
        CHECK(esphome_noise_initiator_init(&hs, PSK, sizeof(PSK), PROLOGUE, sizeof(PROLOGUE),
                                           deterministic_entropy, &counter) == ESPHOME_NOISE_OK,
              "init failed");
        CHECK(esphome_noise_set_fixed_ephemeral(&hs, CLIENT_ENTROPY) == ESPHOME_NOISE_OK, "fixed rejected");
        CHECK(esphome_noise_write_message(&hs, out, sizeof(out), &out_len) == ESPHOME_NOISE_OK, "write failed");
        CHECK(esphome_noise_read_message(&hs, msg, sizeof(msg)) == ESPHOME_NOISE_ERR_AUTH_FAILED,
              "tampered tag bit %u was accepted", bit);
    }
    /* A tampered ephemeral public key must also fail: the DH output changes. */
    memcpy(msg, MSG2, sizeof(msg));
    msg[0] ^= 0x01u;
    CHECK(esphome_noise_initiator_init(&hs, PSK, sizeof(PSK), PROLOGUE, sizeof(PROLOGUE),
                                       deterministic_entropy, &counter) == ESPHOME_NOISE_OK,
          "init failed");
    CHECK(esphome_noise_set_fixed_ephemeral(&hs, CLIENT_ENTROPY) == ESPHOME_NOISE_OK, "fixed rejected");
    CHECK(esphome_noise_write_message(&hs, out, sizeof(out), &out_len) == ESPHOME_NOISE_OK, "write failed");
    CHECK(esphome_noise_read_message(&hs, msg, sizeof(msg)) == ESPHOME_NOISE_ERR_AUTH_FAILED,
          "tampered ephemeral key was accepted");
}

static void test_prologue_is_bound(void)
{
    esphome_noise_handshake_t hs;
    uint8_t out[64];
    size_t out_len = 0;
    uint32_t counter = 0;
    /* Same PSK and ephemeral, different prologue: the first message must differ
     * and the reference response must no longer authenticate. */
    static const uint8_t other_prologue[12] = {0x4e, 0x6f, 0x69, 0x73, 0x65, 0x41, 0x50,
                                               0x49, 0x49, 0x6e, 0x69, 0x75};

    CHECK(esphome_noise_initiator_init(&hs, PSK, sizeof(PSK), other_prologue, sizeof(other_prologue),
                                       deterministic_entropy, &counter) == ESPHOME_NOISE_OK,
          "init failed");
    CHECK(esphome_noise_set_fixed_ephemeral(&hs, CLIENT_ENTROPY) == ESPHOME_NOISE_OK, "fixed rejected");
    CHECK(esphome_noise_write_message(&hs, out, sizeof(out), &out_len) == ESPHOME_NOISE_OK, "write failed");
    CHECK(!same(out + 32, MSG1 + 32, 16), "prologue is not bound into the handshake");
    CHECK(esphome_noise_read_message(&hs, MSG2, sizeof(MSG2)) == ESPHOME_NOISE_ERR_AUTH_FAILED,
          "a mismatched prologue was accepted");
}

static void test_argument_and_state_errors(void)
{
    esphome_noise_handshake_t hs;
    esphome_noise_cipherstate_t send, recv;
    uint8_t out[64];
    size_t out_len = 0;
    uint32_t counter = 0;

    CHECK(esphome_noise_initiator_init(NULL, PSK, 32, NULL, 0, deterministic_entropy, &counter) ==
              ESPHOME_NOISE_ERR_ARG,
          "NULL handshake accepted");
    CHECK(esphome_noise_initiator_init(&hs, PSK, 31, NULL, 0, deterministic_entropy, &counter) ==
              ESPHOME_NOISE_ERR_ARG,
          "31-byte PSK accepted");
    CHECK(esphome_noise_initiator_init(&hs, PSK, 32, NULL, 0, NULL, &counter) == ESPHOME_NOISE_ERR_ARG,
          "NULL entropy accepted");
    CHECK(esphome_noise_initiator_init(&hs, PSK, 32, NULL, 0, deterministic_entropy, NULL) ==
              ESPHOME_NOISE_OK,
          "NULL entropy_user must be allowed");
    /* A NULL entropy_user is legal, but this callback dereferences it, so the
     * session must not be driven any further: reset before the next case. */
    esphome_noise_handshake_wipe(&hs);
    CHECK(esphome_noise_initiator_init(&hs, PSK, 32, NULL, 0, deterministic_entropy, &counter) ==
              ESPHOME_NOISE_OK,
          "re-init after wipe failed");

    /* Writing before reading twice, reading out of turn, and a short buffer. */
    CHECK(esphome_noise_read_message(&hs, MSG2, sizeof(MSG2)) == ESPHOME_NOISE_ERR_STATE,
          "read accepted in the write phase");
    CHECK(esphome_noise_write_message(&hs, out, 47u, &out_len) == ESPHOME_NOISE_ERR_SIZE,
          "undersized buffer accepted");
    CHECK(esphome_noise_write_message(&hs, out, sizeof(out), &out_len) == ESPHOME_NOISE_OK, "write failed");
    CHECK(esphome_noise_write_message(&hs, out, sizeof(out), &out_len) == ESPHOME_NOISE_ERR_STATE,
          "second write accepted");
    CHECK(esphome_noise_write_message(&hs, NULL, sizeof(out), &out_len) == ESPHOME_NOISE_ERR_ARG,
          "NULL output accepted");
    CHECK(esphome_noise_read_message(&hs, MSG2, 47u) == ESPHOME_NOISE_ERR_SIZE,
          "short handshake message accepted");
    CHECK(esphome_noise_step(&hs) == ESPHOME_NOISE_STEP_FAILED, "size failure is not terminal");
    CHECK(esphome_noise_split(&hs, &send, &recv) == ESPHOME_NOISE_ERR_STATE,
          "split accepted on a failed handshake");
    CHECK(esphome_noise_set_fixed_ephemeral(&hs, CLIENT_ENTROPY) == ESPHOME_NOISE_ERR_STATE,
          "fixed ephemeral accepted after the handshake started");

    /* Empty prologue is legal and distinct from the ESPHome prologue. */
    CHECK(esphome_noise_initiator_init(&hs, PSK, 32, NULL, 0, deterministic_entropy, &counter) ==
              ESPHOME_NOISE_OK,
          "empty prologue rejected");
    CHECK(esphome_noise_write_message(&hs, out, sizeof(out), &out_len) == ESPHOME_NOISE_OK,
          "write with an empty prologue failed");
    CHECK(!same(out + 32, MSG1 + 32, 16), "empty prologue produced the ESPHome prologue transcript");
    CHECK(esphome_noise_step(&hs) == ESPHOME_NOISE_STEP_READ, "expected READ");
}

/* ------------------------------------------------------------------ */
/* full exchange against a spec-level responder written here           */
/* ------------------------------------------------------------------ */

static void responder_run(const uint8_t psk[32], const uint8_t prologue[12], const uint8_t *msg1,
                          const uint8_t *e_pub_r, const uint8_t *e_priv_r, uint8_t *msg2_out,
                          uint8_t send_key[32], uint8_t recv_key[32], uint8_t hh[32])
{
    static const char name[] = ESPHOME_NOISE_PROTOCOL_NAME;
    uint8_t h[32], ck[32], k[32], temp_h[32], temp_k[32], new_ck[32], nonce[12];
    uint8_t tag[16];

    noise_sha256(name, sizeof(name) - 1u, h);
    memcpy(ck, h, 32);
    /* MixHash(prologue) */
    noise_sha256_t sha;
    noise_sha256_init(&sha);
    noise_sha256_update(&sha, h, 32);
    noise_sha256_update(&sha, prologue, 12);
    noise_sha256_final(&sha, h);

    /* message 1: psk, e, payload */
    noise_hkdf_sha256(ck, psk, 32, new_ck, temp_h, temp_k, 3u);
    memcpy(ck, new_ck, 32);
    noise_sha256_init(&sha);
    noise_sha256_update(&sha, h, 32);
    noise_sha256_update(&sha, temp_h, 32);
    noise_sha256_final(&sha, h);
    memcpy(k, temp_k, 32);
    memset(nonce, 0, sizeof(nonce));

    noise_sha256_init(&sha);
    noise_sha256_update(&sha, h, 32);
    noise_sha256_update(&sha, msg1, 32);
    noise_sha256_final(&sha, h);
    noise_hkdf_sha256(ck, msg1, 32, new_ck, temp_k, NULL, 2u);
    memcpy(ck, new_ck, 32);
    memcpy(k, temp_k, 32);
    memset(nonce, 0, sizeof(nonce));

    CHECK(noise_aead_decrypt(k, nonce, h, 32, msg1 + 32, 16, tag), "responder could not verify msg1");
    noise_sha256_init(&sha);
    noise_sha256_update(&sha, h, 32);
    noise_sha256_update(&sha, msg1 + 32, 16);
    noise_sha256_final(&sha, h);

    /* message 2: e, ee, payload */
    memcpy(msg2_out, e_pub_r, 32);
    noise_sha256_init(&sha);
    noise_sha256_update(&sha, h, 32);
    noise_sha256_update(&sha, e_pub_r, 32);
    noise_sha256_final(&sha, h);
    noise_hkdf_sha256(ck, e_pub_r, 32, new_ck, temp_k, NULL, 2u);
    memcpy(ck, new_ck, 32);
    memcpy(k, temp_k, 32);
    memset(nonce, 0, sizeof(nonce));

    {
        uint8_t ee[32];
        noise_x25519(ee, e_priv_r, msg1);
        noise_hkdf_sha256(ck, ee, 32, new_ck, temp_k, NULL, 2u);
        memcpy(ck, new_ck, 32);
        memcpy(k, temp_k, 32);
        memset(nonce, 0, sizeof(nonce));
        noise_crypto_wipe(ee, sizeof(ee));
    }

    CHECK(noise_aead_encrypt(k, nonce, h, 32, NULL, 0u, tag), "responder encrypt failed");
    memcpy(msg2_out + 32, tag, 16);
    noise_sha256_init(&sha);
    noise_sha256_update(&sha, h, 32);
    noise_sha256_update(&sha, tag, 16);
    noise_sha256_final(&sha, h);

    memcpy(hh, h, 32);
    noise_hkdf_sha256(ck, NULL, 0u, recv_key, send_key, NULL, 2u);
    noise_crypto_wipe(k, sizeof(k));
    noise_crypto_wipe(ck, sizeof(ck));
    noise_crypto_wipe(h, sizeof(h));
    noise_crypto_wipe(temp_h, sizeof(temp_h));
    noise_crypto_wipe(temp_k, sizeof(temp_k));
    noise_crypto_wipe(new_ck, sizeof(new_ck));
}

static void test_full_exchange_with_fresh_keys(void)
{
    esphome_noise_handshake_t hs;
    esphome_noise_cipherstate_t send, recv;
    uint8_t msg1[48], msg2[48], plain[64];
    uint8_t e_priv_r[32], e_pub_r[32], r_send[32], r_recv[32], r_hh[32], c_hh[32];
    size_t out_len = 0;
    uint32_t counter = 0x12345678u;

    make_keypair(&counter, e_priv_r, e_pub_r);

    CHECK(esphome_noise_initiator_init(&hs, PSK, 32, PROLOGUE, 12, deterministic_entropy, &counter) ==
              ESPHOME_NOISE_OK,
          "init failed");
    CHECK(esphome_noise_write_message(&hs, msg1, sizeof(msg1), &out_len) == ESPHOME_NOISE_OK, "write failed");
    CHECK(out_len == 48u, "msg1 length");

    responder_run(PSK, PROLOGUE, msg1, e_pub_r, e_priv_r, msg2, r_send, r_recv, r_hh);

    CHECK(esphome_noise_read_message(&hs, msg2, sizeof(msg2)) == ESPHOME_NOISE_OK, "read failed");
    CHECK(esphome_noise_split(&hs, &send, &recv) == ESPHOME_NOISE_OK, "split failed");
    CHECK(esphome_noise_handshake_hash(&hs, c_hh) == ESPHOME_NOISE_OK, "hash failed");
    CHECK(same(send.key, r_recv, 32), "initiator send key does not match the responder receive key");
    CHECK(same(recv.key, r_send, 32), "initiator receive key does not match the responder send key");
    CHECK(same(c_hh, r_hh, 32), "handshake hashes differ");

    /* Responder -> initiator transport, then initiator -> responder. */
    {
        uint8_t frame[64];
        size_t frame_len = 0;
        esphome_noise_cipherstate_t rs;
        CHECK(esphome_noise_cipherstate_init(&rs, r_send) == ESPHOME_NOISE_OK, "responder cipher init");
        CHECK(esphome_noise_encrypt(&rs, NULL, 0u, (const uint8_t *)"\x00\x13\x00\x00", 4u, frame,
                                    sizeof(frame), &frame_len) == ESPHOME_NOISE_OK,
              "responder encrypt failed");
        CHECK(esphome_noise_decrypt(&recv, NULL, 0u, frame, frame_len, plain, sizeof(plain), &out_len) ==
                  ESPHOME_NOISE_OK,
              "initiator decrypt failed");
        CHECK(out_len == 4u && plain[1] == 0x13, "decrypted responder packet is wrong");
        esphome_noise_cipherstate_wipe(&rs);
    }
    {
        uint8_t frame[64];
        size_t frame_len = 0;
        esphome_noise_cipherstate_t rr;
        CHECK(esphome_noise_cipherstate_init(&rr, r_recv) == ESPHOME_NOISE_OK, "responder cipher init");
        CHECK(esphome_noise_encrypt(&send, NULL, 0u, (const uint8_t *)"\x00\x21\x00\x00", 4u, frame,
                                    sizeof(frame), &frame_len) == ESPHOME_NOISE_OK,
              "initiator encrypt failed");
        CHECK(esphome_noise_decrypt(&rr, NULL, 0u, frame, frame_len, plain, sizeof(plain), &out_len) ==
                  ESPHOME_NOISE_OK,
              "responder decrypt failed");
        CHECK(out_len == 4u && plain[1] == 0x21, "decrypted initiator packet is wrong");
        esphome_noise_cipherstate_wipe(&rr);
    }
}

/* ------------------------------------------------------------------ */
/* transport cipherstate behaviour                                     */
/* ------------------------------------------------------------------ */

static void test_transport_cipherstate(void)
{
    esphome_noise_cipherstate_t cs, other;
    uint8_t key[32];
    uint8_t frame[64];
    /* Sized for the largest plaintext any case here can produce, so a failed
     * decrypt can never be confused with a buffer that is too small. */
    uint8_t plain[64];
    size_t out_len = 0;

    for (unsigned i = 0; i < 32u; i++) {
        key[i] = (uint8_t)(i + 1u);
    }
    CHECK(esphome_noise_cipherstate_init(&cs, key) == ESPHOME_NOISE_OK, "cipher init failed");
    CHECK(esphome_noise_cipherstate_init(&other, key) == ESPHOME_NOISE_OK, "cipher init failed");

    CHECK(esphome_noise_encrypt(&cs, NULL, 0u, (const uint8_t *)"abcd", 4u, frame, sizeof(frame),
                                &out_len) == ESPHOME_NOISE_OK,
          "encrypt failed");
    CHECK(out_len == 20u, "frame length %u", (unsigned)out_len);

    /* A failed decrypt must not consume a nonce, and the frame must still be
     * usable afterwards: the failure path must not have mutated any state. */
    {
        uint8_t bad[20];
        size_t bad_len = 0;
        memcpy(bad, frame, sizeof(bad));
        bad[19] ^= 0x80u;
        CHECK(esphome_noise_decrypt(&other, NULL, 0u, bad, sizeof(bad), plain, sizeof(plain), &bad_len) ==
                  ESPHOME_NOISE_ERR_AUTH_FAILED,
              "tampered frame accepted");
        CHECK(other.nonce == 0u, "a failed decrypt consumed a nonce");
        CHECK(bad_len == 0u, "a failed decrypt reported an output length");
        CHECK(esphome_noise_decrypt(&other, NULL, 0u, frame, out_len, plain, sizeof(plain),
                                    &out_len) == ESPHOME_NOISE_OK,
              "valid frame rejected after a failed attempt");
        CHECK(out_len == 4u && memcmp(plain, "abcd", 4u) == 0, "plaintext mismatch");
        CHECK(other.nonce == 1u, "successful decrypt did not consume exactly one nonce");
    }

    /* Replay of the same frame must fail because the nonce has moved on. */
    CHECK(esphome_noise_decrypt(&other, NULL, 0u, frame, 20u, plain, sizeof(plain), &out_len) ==
              ESPHOME_NOISE_ERR_AUTH_FAILED,
          "replayed frame accepted");

    /* Associated data is authenticated. */
    {
        uint8_t ad[4] = {1u, 2u, 3u, 4u};
        CHECK(esphome_noise_cipherstate_init(&cs, key) == ESPHOME_NOISE_OK, "cipher init failed");
        CHECK(esphome_noise_cipherstate_init(&other, key) == ESPHOME_NOISE_OK, "cipher init failed");
        CHECK(esphome_noise_encrypt(&cs, ad, sizeof(ad), (const uint8_t *)"abcd", 4u, frame, sizeof(frame),
                                    &out_len) == ESPHOME_NOISE_OK,
              "encrypt with ad failed");
        ad[0] = 9u;
        CHECK(esphome_noise_decrypt(&other, ad, sizeof(ad), frame, out_len, plain, sizeof(plain),
                                    &out_len) == ESPHOME_NOISE_ERR_AUTH_FAILED,
              "modified associated data was accepted");
    }

    /* Buffer bounds and nonce exhaustion. */
    CHECK(esphome_noise_encrypt(&cs, NULL, 0u, (const uint8_t *)"abcd", 4u, frame, 19u, &out_len) ==
              ESPHOME_NOISE_ERR_SIZE,
          "undersized output accepted");
    CHECK(esphome_noise_decrypt(&cs, NULL, 0u, frame, 15u, plain, sizeof(plain), &out_len) ==
              ESPHOME_NOISE_ERR_SIZE,
          "undersized ciphertext accepted");
    {
        esphome_noise_cipherstate_t exhausted;
        CHECK(esphome_noise_cipherstate_init(&exhausted, key) == ESPHOME_NOISE_OK, "cipher init failed");
        exhausted.nonce = UINT64_MAX;
        CHECK(esphome_noise_encrypt(&exhausted, NULL, 0u, NULL, 0u, frame, sizeof(frame), &out_len) ==
                  ESPHOME_NOISE_ERR_STATE,
              "nonce exhaustion not detected");
        CHECK(exhausted.nonce == UINT64_MAX, "exhausted nonce moved");
    }

    /* Rekey changes the key but not the nonce, and both sides stay in step. */
    {
        esphome_noise_cipherstate_t a, b;
        uint8_t saved_nonce;
        CHECK(esphome_noise_cipherstate_init(&a, key) == ESPHOME_NOISE_OK, "cipher init failed");
        CHECK(esphome_noise_cipherstate_init(&b, key) == ESPHOME_NOISE_OK, "cipher init failed");
        saved_nonce = (uint8_t)a.nonce;
        CHECK(esphome_noise_cipherstate_rekey(&a) == ESPHOME_NOISE_OK, "rekey failed");
        CHECK(esphome_noise_cipherstate_rekey(&b) == ESPHOME_NOISE_OK, "rekey failed");
        CHECK(same(a.key, b.key, 32), "rekey is not deterministic");
        CHECK(!same(a.key, key, 32), "rekey did not change the key");
        CHECK((uint8_t)a.nonce == saved_nonce, "rekey changed the nonce");
        CHECK(esphome_noise_encrypt(&a, NULL, 0u, (const uint8_t *)"xyz", 3u, frame, sizeof(frame),
                                    &out_len) == ESPHOME_NOISE_OK,
              "encrypt after rekey failed");
        CHECK(esphome_noise_decrypt(&b, NULL, 0u, frame, out_len, plain, sizeof(plain), &out_len) ==
                  ESPHOME_NOISE_OK,
              "decrypt after rekey failed");
    }

    /* A wiped cipherstate must refuse to operate. */
    esphome_noise_cipherstate_wipe(&cs);
    CHECK(!cs.has_key, "wipe left the key flag set");
    CHECK(esphome_noise_encrypt(&cs, NULL, 0u, NULL, 0u, frame, sizeof(frame), &out_len) ==
              ESPHOME_NOISE_ERR_STATE,
          "wiped cipherstate still encrypts");
}

/* Frames pinned by tools/reference/noise_transport_reference.py: the same
 * transport keys as the reference handshake, driven through a short packet
 * sequence. This is the only place the frame counter is checked against an
 * independent implementation over more than one message, so a nonce that
 * stops advancing, advances twice, or is built in the wrong byte order fails
 * here rather than silently breaking interop on the second packet. */
static void test_transport_frame_sequence(void)
{
    static const struct {
        uint8_t type;
        const uint8_t *payload;
        size_t payload_len;
    } sent_plain[] = {
        {1u, NULL, 0u},
        {9u, NULL, 0u},
        {11u, NULL, 0u},
        {20u, NULL, 0u},
        {33u, (const uint8_t *)"\x11\x11\x11\x11\x08\x00", 6u},
    };
    static const struct {
        const uint8_t *frame;
        size_t frame_len;
    } sent_frames[] = {
        {SENT_0, sizeof(SENT_0)},
        {SENT_1, sizeof(SENT_1)},
        {SENT_2, sizeof(SENT_2)},
        {SENT_3, sizeof(SENT_3)},
        {SENT_4, sizeof(SENT_4)},
    };
    static const struct {
        const uint8_t *frame;
        size_t frame_len;
        uint8_t type;
        const uint8_t *payload;
        size_t payload_len;
    } recvd_frames[] = {
        {RECVD_0, sizeof(RECVD_0), 2u, (const uint8_t *)"\x0a\x00", 2u},
        {RECVD_1, sizeof(RECVD_1), 26u, (const uint8_t *)"\x11\x11\x11\x11\x08\x01", 6u},
    };

    esphome_noise_cipherstate_t send, recv;
    /* Sized for the largest ciphertext in the sequence (3 + 4 + 6 + 16) and the
     * largest plaintext it can decrypt (4 + 6), so a length mismatch can never
     * be mistaken for a buffer that was too small. */
    uint8_t frame[29];
    uint8_t plain[10];
    size_t frame_len = 0;
    size_t plain_len = 0;
    size_t i;

    CHECK(sizeof(sent_plain) / sizeof(sent_plain[0]) == sizeof(sent_frames) / sizeof(sent_frames[0]),
          "fixture tables disagree on the number of client packets");

    CHECK(esphome_noise_cipherstate_init(&send, SEND_KEY) == ESPHOME_NOISE_OK, "send cipher init failed");
    CHECK(esphome_noise_cipherstate_init(&recv, RECV_KEY) == ESPHOME_NOISE_OK, "recv cipher init failed");

    for (i = 0u; i < sizeof(sent_plain) / sizeof(sent_plain[0]); i++) {
        /* The plaintext is the ESPHome frame header (msg type, then payload
         * length, both big-endian) followed by the body. The header is encrypted
         * rather than authenticated as associated data, which is what keeps the
         * total overhead at 3 + 4 + 16 bytes per frame. */
        uint8_t pt[4u + 8u];
        size_t pt_len = 4u + sent_plain[i].payload_len;
        /* The pinned frames carry the 3-byte session prefix (0x01 plus the
         * big-endian ciphertext length); esphome_noise_encrypt produces only
         * the ciphertext, so the comparison starts past that prefix. */
        size_t body_len = sent_frames[i].frame_len - 3u;

        pt[0] = 0x00;
        pt[1] = sent_plain[i].type;
        pt[2] = (uint8_t)(sent_plain[i].payload_len >> 8);
        pt[3] = (uint8_t)(sent_plain[i].payload_len & 0xffu);
        if (sent_plain[i].payload_len != 0u) {
            memcpy(pt + 4u, sent_plain[i].payload, sent_plain[i].payload_len);
        }

        CHECK(send.nonce == (uint64_t)i, "send nonce is %llu before packet %u",
              (unsigned long long)send.nonce, (unsigned)i);

        CHECK(esphome_noise_encrypt(&send, NULL, 0u, pt, pt_len, frame, sizeof(frame), &frame_len) ==
                  ESPHOME_NOISE_OK,
              "packet %u failed to encrypt", (unsigned)i);
        CHECK(frame_len == body_len, "packet %u is %u bytes, expected %u",
              (unsigned)i, (unsigned)frame_len, (unsigned)body_len);
        CHECK(frame_len <= sizeof(frame) && same(frame, sent_frames[i].frame + 3u, body_len),
              "packet %u does not match the reference bytes", (unsigned)i);
        /* The prefix the session prepends must also agree, or a peer would
         * drop the frame before it ever reached the AEAD. */
        CHECK(sent_frames[i].frame[0] == 0x01u &&
                  sent_frames[i].frame[1] == (uint8_t)(body_len >> 8) &&
                  sent_frames[i].frame[2] == (uint8_t)(body_len & 0xffu),
              "packet %u has a malformed session prefix", (unsigned)i);
        CHECK(send.nonce == (uint64_t)i + 1u, "send nonce did not advance exactly once on packet %u",
              (unsigned)i);
    }

    for (i = 0u; i < sizeof(recvd_frames) / sizeof(recvd_frames[0]); i++) {
        const uint8_t *body = recvd_frames[i].frame + 3u;
        size_t body_len = recvd_frames[i].frame_len - 3u;

        CHECK(recv.nonce == (uint64_t)i, "recv nonce is %llu before frame %u",
              (unsigned long long)recv.nonce, (unsigned)i);
        CHECK(esphome_noise_decrypt(&recv, NULL, 0u, body, body_len, plain, sizeof(plain),
                                    &plain_len) == ESPHOME_NOISE_OK,
              "frame %u failed to decrypt", (unsigned)i);
        CHECK(plain_len == 4u + recvd_frames[i].payload_len,
              "frame %u decrypted to %u bytes, expected %u", (unsigned)i, (unsigned)plain_len,
              (unsigned)(4u + recvd_frames[i].payload_len));
        /* The decrypted header must agree with what the responder claims to
         * have sent, which is what esphome_api's unwrap path relies on. */
        CHECK(plain[0] == 0x00 && plain[1] == recvd_frames[i].type &&
                  plain[2] == (uint8_t)(recvd_frames[i].payload_len >> 8) &&
                  plain[3] == (uint8_t)(recvd_frames[i].payload_len & 0xffu),
              "frame %u decrypted to a header reporting type %u length %u", (unsigned)i,
              (unsigned)plain[1], (unsigned)(((uint16_t)plain[2] << 8) | plain[3]));
        CHECK(plain_len - 4u <= sizeof(plain) &&
                  same(plain + 4u, recvd_frames[i].payload, plain_len - 4u),
              "frame %u decrypted to the wrong payload", (unsigned)i);
        CHECK(recv.nonce == (uint64_t)i + 1u, "recv nonce did not advance exactly once on frame %u",
              (unsigned)i);
    }

    /* The first client packet is the ESPHome client hello: the handshake
     * marker (0x00 0x01 0x00 0x00) is sent before the framing starts, and this
     * is the first framed packet after it. Its length is pinned so that a
     * reader of these vectors can tell where the marker ends and the ciphertext
     * begins without counting bytes by hand. */
    CHECK(sent_frames[0].frame_len == 23u, "the first client frame is %u bytes, expected 23",
          (unsigned)sent_frames[0].frame_len);
    CHECK(sent_plain[0].type == 1u, "the first client packet is not HelloRequest");
    CHECK(sent_plain[0].payload_len == 0u, "HelloRequest must have an empty body");

    esphome_noise_cipherstate_wipe(&send);
    esphome_noise_cipherstate_wipe(&recv);
}

/* ------------------------------------------------------------------ */
/* the two implementations, against each other, on a non-pinned input   */
/* ------------------------------------------------------------------ */

/*
 * An ephemeral private key, so nothing in this test can pass by matching a fixture that
 * both implementations were written against.
 */
static const uint8_t PAIR_CLIENT_ENTROPY[32] = {
    0xa1, 0xa2, 0xa3, 0xa4, 0xa5, 0xa6, 0xa7, 0xa8, 0xa9, 0xaa, 0xab, 0xac, 0xad, 0xae, 0xaf, 0xb0,
    0xb1, 0xb2, 0xb3, 0xb4, 0xb5, 0xb6, 0xb7, 0xb8, 0xb9, 0xba, 0xbb, 0xbc, 0xbd, 0xbe, 0xbf, 0xc0};
static const uint8_t PAIR_SERVER_ENTROPY[32] = {
    0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f, 0x30,
    0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x3b, 0x3c, 0x3d, 0x3e, 0x3f, 0x40};
static const uint8_t PAIR_PSK[32] = {
    0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff, 0x00,
    0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10};

static void pair_client_entropy(void *user, uint8_t *out, size_t len)
{
    (void)user;
    memcpy(out, PAIR_CLIENT_ENTROPY, len);
}

/*
 * The firmware's initiator against the repository's spec responder, in one process, on
 * an input neither was written against.
 *
 * Why this test exists, and what it covers that the others cannot:
 *
 *   - test_pinned_handshake checks the initiator against bytes an independent Python
 *     implementation produced. Strong, but it is a FIXED input: two implementations can
 *     agree on a fixture and still disagree in general.
 *   - test_full_exchange_with_fresh_keys drives the responder with freshly generated
 *     keys, but only through the assertions written here.
 *   - test_api_client is the only test that puts the two against each other over a real
 *     socket - and it is the one that has been failing, on a two-byte divergence in
 *     message 2, for several rounds. It cannot be compiled on Windows (no POSIX socket
 *     headers) and its local port does not survive the five sequential connections it
 *     makes, so the failure has never been reproducible off CI.
 *
 * This closes that gap WITHOUT sockets: the same two implementations, the same
 * handshake, one process, no transport. It asserts the four things that have to hold
 * between two independent implementations - the responder accepts the initiator's
 * message 1, the initiator accepts the responder's message 2, the transport keys cross,
 * and the handshake hashes agree - and it does so on an input that is not a fixture.
 *
 * What it does NOT cover: the framing on a real stream, and the socket path. Those stay
 * with test_api_client on CI.
 */
static void test_the_two_implementations_agree(void)
{
    esphome_noise_handshake_t initiator;
    ntr_state_t responder;
    uint8_t msg1[ESPHOME_NOISE_HANDSHAKE_MSG_BYTES];
    uint8_t msg2[ESPHOME_NOISE_HANDSHAKE_MSG_BYTES];
    esphome_noise_cipherstate_t i_send, i_recv;
    uint8_t r_send[32], r_recv[32];
    uint8_t i_hh[32], r_hh[32];
    size_t msg_len = 0u;

    ntr_reset(&responder, PAIR_PSK, PROLOGUE, PAIR_SERVER_ENTROPY, NULL);

    CHECK(esphome_noise_initiator_init(&initiator, PAIR_PSK, sizeof(PAIR_PSK), PROLOGUE,
                                       sizeof(PROLOGUE), pair_client_entropy, NULL) ==
              ESPHOME_NOISE_OK,
          "the initiator refused the inputs");

    CHECK(esphome_noise_write_message(&initiator, msg1, sizeof(msg1), &msg_len) ==
              ESPHOME_NOISE_OK,
          "the initiator could not write message 1");
    CHECK(msg_len == sizeof(msg1), "message 1 is %u bytes", (unsigned)msg_len);

    /* The responder verifies the initiator's tag: this is where a wrong PSK, prologue or
     * key schedule shows up as a rejection rather than as a later mismatch. */
    CHECK(ntr_handshake(&responder, msg1, msg2),
          "the responder rejected the initiator's message 1");

    /* And the initiator verifies the responder's. A two-byte divergence in this tag is
     * exactly what test_api_client reports, so this assertion is the one that would
     * catch it here instead. */
    CHECK(esphome_noise_read_message(&initiator, msg2, sizeof(msg2)) == ESPHOME_NOISE_OK,
          "the initiator rejected the responder's message 2");
    CHECK(esphome_noise_step(&initiator) == ESPHOME_NOISE_STEP_DONE,
          "the initiator's handshake did not complete");
    CHECK(responder.ready, "the responder's handshake did not complete");

    CHECK(esphome_noise_split(&initiator, &i_send, &i_recv) == ESPHOME_NOISE_OK,
          "the initiator's split failed");
    CHECK(ntr_split(&responder, r_send, r_recv), "the responder's split failed");

    /* Keys cross, and they cross on the FULL 32 bytes: a comparison that only looked at
     * the first 30 would have missed the divergence this test was written for. */
    CHECK(same(i_send.key, r_recv, 32),
          "the initiator's send key is not the responder's receive key");
    CHECK(same(i_recv.key, r_send, 32),
          "the initiator's receive key is not the responder's send key");
    CHECK(!same(i_send.key, i_recv.key, 32),
          "the two directions produced the same key, so the split is not crossing them");

    CHECK(esphome_noise_handshake_hash(&initiator, i_hh) == ESPHOME_NOISE_OK,
          "the initiator's handshake hash is unavailable");
    memcpy(r_hh, responder.h, 32);
    CHECK(same(i_hh, r_hh, 32), "the two implementations disagree on the handshake hash");
}

/*
 * REMOVED ON PURPOSE: a transport-frame exchange between the two implementations.
 *
 * It was written, it did not work, and the reason is structural rather than a bug
 * worth chasing. ntr_state_t keeps ONE nonce for both directions, so a frame it seals
 * is not decryptable by a freshly split esphome_noise_cipherstate_t on the other side
 * unless the nonce is set by hand - to a value that depends on how many frames had gone
 * each way, which is a state the protocol never produces. Setting it by hand would make
 * the test an assertion about the harness.
 *
 * What needs proving about frames is already pinned, and pinned better:
 *   - test_transport_frame_sequence() checks seven whole frames, both directions, byte
 *     for byte against the independent Python reference, including the nonce sequence;
 *   - test_the_two_implementations_agree() checks the two state machines against each
 *     other on a non-pinned input, which is the part a fixed fixture cannot cover.
 */

static void test_struct_sizes(void)
{
    /* The firmware session embeds these; an unexpected growth is a silent
     * flash/RAM increase, so pin a bound that both 32-bit and 64-bit ABIs
     * satisfy. */
    printf("  sizeof(cipherstate) = %u, sizeof(handshake) = %u\n",
           (unsigned)sizeof(esphome_noise_cipherstate_t),
           (unsigned)sizeof(esphome_noise_handshake_t));
    CHECK(sizeof(esphome_noise_cipherstate_t) <= 48u, "cipherstate is %u bytes",
          (unsigned)sizeof(esphome_noise_cipherstate_t));
    CHECK(sizeof(esphome_noise_handshake_t) <= 256u, "handshake state is %u bytes",
          (unsigned)sizeof(esphome_noise_handshake_t));
}

int main(void)
{
    test_pinned_handshake();
    test_pinned_wrong_psk_is_rejected();
    test_tampered_handshake_message_is_rejected();
    test_prologue_is_bound();
    test_argument_and_state_errors();
    test_full_exchange_with_fresh_keys();
    test_transport_cipherstate();
    test_transport_frame_sequence();
    test_the_two_implementations_agree();
    test_struct_sizes();

    if (failures != 0) {
        printf("noise tests: %d failure(s)\n", failures);
        return 1;
    }
    printf("noise tests: ok\n");
    return 0;
}
