#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <string.h>
#include "private/esphome_api_codec.h"
int main(void){uint8_t b[512];size_t n;assert(esphome_api_codec_hello_request(b,sizeof(b),&n)&&n>0);esphome_pb_writer_t w;esphome_pb_writer_init(&w,b,sizeof(b));esphome_pb_put_varint(&w,1,1);esphome_pb_put_varint(&w,2,15);esphome_pb_put_string(&w,3,"ESPHome 2026.8",32);esphome_pb_put_string(&w,4,"node",31);esphome_api_probe_result_t p={0};assert(esphome_api_codec_parse_hello(b,w.len,&p)&&p.api_version_minor==15&&!strcmp(p.name,"node"));
esphome_pb_writer_init(&w,b,sizeof(b));esphome_pb_put_string(&w,2,"node",31);esphome_pb_put_string(&w,3,"AA:BB:CC:DD:EE:FF",17);esphome_pb_put_string(&w,4,"2026.8.0",32);esphome_pb_put_bool(&w,19,true);assert(esphome_api_codec_parse_device_info(b,w.len,&p)&&!strcmp(p.esphome_version,"2026.8.0")&&p.api_encryption_supported);
esphome_pb_writer_init(&w,b,sizeof(b));esphome_pb_put_string(&w,1,"relay",120);esphome_pb_put_fixed32(&w,2,0x11223344);esphome_pb_put_string(&w,3,"Relay",120);esphome_pb_put_bool(&w,6,true);esphome_pb_put_varint(&w,8,1);esphome_pb_put_string(&w,9,"outlet",47);esphome_pb_put_varint(&w,10,2);esphome_api_entity_t e;assert(esphome_api_codec_parse_entity(17,b,w.len,&e)&&e.kind==ESPHOME_API_ENTITY_SWITCH&&e.key==0x11223344&&e.detail.switch_.assumed_state&&e.device_id==2&&!strcmp(e.device_class,"outlet"));
esphome_pb_writer_init(&w,b,sizeof(b));esphome_pb_put_string(&w,1,"temp",120);esphome_pb_put_fixed32(&w,2,7);esphome_pb_put_string(&w,3,"Temp",120);esphome_pb_put_string(&w,6,"C",63);esphome_pb_put_varint(&w,7,2);esphome_pb_put_string(&w,9,"temperature",47);esphome_pb_put_varint(&w,10,1);assert(esphome_api_codec_parse_entity(16,b,w.len,&e)&&e.kind==ESPHOME_API_ENTITY_SENSOR&&!strcmp(e.unit,"C")&&e.detail.sensor.accuracy_decimals==2);
esphome_pb_writer_init(&w,b,sizeof(b));esphome_pb_put_fixed32(&w,1,7);esphome_pb_put_float(&w,2,23.5f);esphome_pb_put_bool(&w,3,false);esphome_api_state_t st;assert(esphome_api_codec_parse_state(25,b,w.len,&st)&&st.key==7&&fabsf(st.value.number-23.5f)<.001f);
esphome_api_command_t cmd={.kind=ESPHOME_API_COMMAND_SWITCH,.key=0xAABBCCDD,.value.switch_.state=true};uint16_t type;assert(esphome_api_codec_command(&cmd,&type,b,sizeof(b),&n)&&type==33);esphome_pb_reader_t rd;esphome_pb_reader_init(&rd,b,n);uint32_t f,fx;uint8_t wire;uint64_t v;const uint8_t*p2;size_t l;assert(esphome_pb_next(&rd,&f,&wire,&v,&p2,&l,&fx)&&f==1&&wire==5&&fx==0xAABBCCDD);assert(esphome_pb_next(&rd,&f,&wire,&v,&p2,&l,&fx)&&f==2&&wire==0&&v==1);
uint8_t bad[]={0x0b};esphome_pb_reader_init(&rd,bad,sizeof(bad));assert(!esphome_pb_next(&rd,&f,&wire,&v,&p2,&l,&fx)&&rd.failed);puts("codec tests: ok");return 0;}
